# ModernBERT RAG (Rebalanced Dataset)

# Setup

In [1]:
import datasets
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import json
from google.colab import drive, userdata
from huggingface_hub import login, hf_hub_download

cache_path = "/content/huggingface_cache"
os.makedirs(cache_path, exist_ok=True)
os.environ['HF_HOME'] = cache_path

if userdata.get('HF_TOKEN'):
  login(token=userdata.get('HF_TOKEN'))
  hf_hub_download(repo_id="sookiemonster/asrs-narratives", filename="utils.py", repo_type="dataset",local_dir=".")
  hf_hub_download(repo_id="sookiemonster/asrs-narratives", filename="all_contributing_factors.csv", repo_type="dataset",local_dir=".")

raw_dataset = datasets.load_dataset("sookiemonster/asrs-narratives")
factors = pd.read_csv("all_contributing_factors.csv", index_col=0)

utils.py: 0.00B [00:00, ?B/s]

all_contributing_factors.csv: 0.00B [00:00, ?B/s]

README.md: 0.00B [00:00, ?B/s]

data/train-00000-of-00001.parquet:   0%|          | 0.00/9.74M [00:00<?, ?B/s]

data/validation-00000-of-00001.parquet:   0%|          | 0.00/4.09M [00:00<?, ?B/s]

data/test-00000-of-00001.parquet:   0%|          | 0.00/9.38M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/10360 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/4441 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/9868 [00:00<?, ? examples/s]

In [2]:
train_ds = datasets.load_dataset("sookiemonster/asrs-narratives-rebalance", split='train')
valid_ds = raw_dataset['validation']
test_ds = raw_dataset['test']

labels = train_ds.features['label'].names

id_to_label = { idx : label for idx, label in enumerate(labels) }
label_to_id = { label : idx for idx, label in id_to_label.items() }

README.md: 0.00B [00:00, ?B/s]

data/train-00000-of-00001.parquet:   0%|          | 0.00/22.8M [00:00<?, ?B/s]

data/validation-00000-of-00001.parquet:   0%|          | 0.00/4.09M [00:00<?, ?B/s]

data/test-00000-of-00001.parquet:   0%|          | 0.00/9.38M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/22992 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/4441 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/9868 [00:00<?, ? examples/s]

In [3]:
from functools import partial

def filter_labels(ds, to_remove:list):
  to_remove_set = set(to_remove)
  return ds.filter(lambda example : id_to_label[example['label']] not in to_remove_set)

filter_ambiguous = partial(filter_labels, to_remove=['ambiguous'])

filtered_train_ds = filter_ambiguous(train_ds)
filtered_valid_ds = filter_ambiguous(valid_ds)

Filter:   0%|          | 0/22992 [00:00<?, ? examples/s]

Filter:   0%|          | 0/4441 [00:00<?, ? examples/s]

In [4]:
def _validate_groupings(groupings:dict[str, set]):
  mut_excl = [va.isdisjoint(vb) for ka, va in groupings.items() for kb, vb in groupings.items() if ka != kb]
  assert all(mut_excl), f"{mut_excl}"

  all_labels = set([label for val_set in groupings.values() for label in val_set])
  assert all_labels == set(id_to_label.values()), f"Missing: {set(id_to_label.values()) - all_labels}"


def group_labels(ds, groupings:dict[str, set]):
  _validate_groupings(groupings)
  group_names = list(groupings.keys())
  group_names.sort()

  fine_grained_label_to_group = {
      label : group_name for group_name, val_set in groupings.items() for label in val_set
  }

  res = ds.map(lambda ex: {"group" : fine_grained_label_to_group[ id_to_label[ex['label']] ]})
  res = res.filter(lambda ex: ex["group"] != 'DELETE')

  new_features = res.features.copy()
  group_names.remove("DELETE")
  new_features["group"] = ClassLabel(names=group_names)

  res = res.cast(new_features)
  return res

## Setup Dataset

In [5]:
from datasets import ClassLabel

groupings = {
    'DELETE' : set(['ambiguous']),
}

groupings = groupings | {
    label : set([label]) for label in id_to_label.values() if label != 'ambiguous'
}

grouped_ds_train = group_labels(filtered_train_ds, groupings)
grouped_ds_valid = group_labels(filtered_valid_ds, groupings)

Map:   0%|          | 0/22157 [00:00<?, ? examples/s]

Filter:   0%|          | 0/22157 [00:00<?, ? examples/s]

Casting the dataset:   0%|          | 0/22157 [00:00<?, ? examples/s]

Map:   0%|          | 0/4083 [00:00<?, ? examples/s]

Filter:   0%|          | 0/4083 [00:00<?, ? examples/s]

Casting the dataset:   0%|          | 0/4083 [00:00<?, ? examples/s]

In [6]:
id_to_group = { i: group for i, group in enumerate(grouped_ds_train.features['group'].names) }
id_to_group

{0: 'aircraft',
 1: 'airport',
 2: 'airspacestructure',
 3: 'atcequipment/navfacility/buildings',
 4: 'chartorpublication',
 5: 'companypolicy',
 6: 'environment-nonweatherrelated',
 7: 'equipment/tooling',
 8: 'humanfactors',
 9: 'incorrect/notinstalled/unavailablepart',
 10: 'logbookentry',
 11: 'manuals',
 12: 'mel',
 13: 'procedure',
 14: 'softwareandautomation',
 15: 'staffing',
 16: 'weather'}

# Inference

## Install Flash-Attention

In [7]:
import torch
import sys

print(f"Python Version: {sys.version_info.major}.{sys.version_info.minor}")
print(f"PyTorch Version: {torch.__version__.split('+')[0]}")
print(f"CUDA Version (Torch): {torch.version.cuda}")
print(f"CXX11 ABI: {torch._C._GLIBCXX_USE_CXX11_ABI}")

Python Version: 3.12
PyTorch Version: 2.10.0
CUDA Version (Torch): 12.8
CXX11 ABI: True

In [ ]:
!pip install "https://github.com/lesj0610/flash-attention/releases/download/v2.8.3-cu12-torch2.10-cp312/flash_attn-2.8.3%2Bcu12torch2.10cxx11abiTRUE-cp312-cp312-linux_x86_64.whl"

Collecting flash-attn==2.8.3+cu12torch2.10cxx11abiTRUE
  Downloading https://github.com/lesj0610/flash-attention/releases/download/v2.8.3-cu12-torch2.10-cp312/flash_attn-2.8.3%2Bcu12torch2.10cxx11abiTRUE-cp312-cp312-linux_x86_64.whl (253.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 253.6/253.6 MB 5.1 MB/s eta 0:00:00
Requirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (from flash-attn==2.8.3+cu12torch2.10cxx11abiTRUE) (2.10.0+cu128)
Requirement already satisfied: einops in /usr/local/lib/python3.12/dist-packages (from flash-attn==2.8.3+cu12torch2.10cxx11abiTRUE) (0.8.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch->flash-attn==2.8.3+cu12torch2.10cxx11abiTRUE) (3.29.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch->flash-attn==2.8.3+cu12torch2.10cxx11abiTRUE) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch->flash-attn==2.8.3+cu12torch2.10cxx11abiTRUE) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch->flash-attn==2.8.3+cu12torch2.10cxx11abiTRUE) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch->flash-attn==2.8.3+cu12torch2.10cxx11abiTRUE) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch->flash-attn==2.8.3+cu12torch2.10cxx11abiTRUE) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch->flash-attn==2.8.3+cu12torch2.10cxx11abiTRUE) (2025.3.0)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch->flash-attn==2.8.3+cu12torch2.10cxx11abiTRUE) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch->flash-attn==2.8.3+cu12torch2.10cxx11abiTRUE) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch->flash-attn==2.8.3+cu12torch2.10cxx11abiTRUE) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch->flash-attn==2.8.3+cu12torch2.10cxx11abiTRUE) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch->flash-attn==2.8.3+cu12torch2.10cxx11abiTRUE) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch->flash-attn==2.8.3+cu12torch2.10cxx11abiTRUE) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch->flash-attn==2.8.3+cu12torch2.10cxx11abiTRUE) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch->flash-attn==2.8.3+cu12torch2.10cxx11abiTRUE) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch->flash-attn==2.8.3+cu12torch2.10cxx11abiTRUE) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch->flash-attn==2.8.3+cu12torch2.10cxx11abiTRUE) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch->flash-attn==2.8.3+cu12torch2.10cxx11abiTRUE) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch->flash-attn==2.8.3+cu12torch2.10cxx11abiTRUE) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch->flash-attn==2.8.3+cu12torch2.10cxx11abiTRUE) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch->flash-attn==2.8.3+cu12torch2.10cxx11abiTRUE) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch->flash-attn==2.8.3+cu12torch2.10cxx11abiTRUE) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch->flash-attn==2.8.3+cu12torch2.10cxx11abiTRUE) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch->flash-attn==2.8.3+cu12torch2.10cxx11abiTRUE) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch->flash-attn==2.8.3+cu12torch2.10cxx11abiTRUE) (1.5.3)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch->flash-attn==2.8.3+cu12torch2.10cxx11abiTRUE) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch->flash-attn==2.8.3+cu12torch2.10cxx11abiTRUE) (3.0.3)
Installing collected packages: flash-attn
Successfully installed flash-attn-2.8.3

## Run Model

In [8]:
from sentence_transformers import SentenceTransformer

tuned_model = "sookiemonster/asrs-modernbert-rebalance-weighted"
model = SentenceTransformer(tuned_model)

config.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/299M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/134 [00:00<?, ?it/s]

ModernBertModel LOAD REPORT from: sookiemonster/asrs-modernbert-rebalance-weighted
Key               | Status     |  |
------------------+------------+--+-
head.norm.weight  | UNEXPECTED |  |
classifier.weight | UNEXPECTED |  |
head.dense.weight | UNEXPECTED |  |
classifier.bias   | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json:   0%|          | 0.00/390 [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

In [ ]:
sentences = list(grouped_ds_train['text'])
print(len(sentences))
sentences[:5]

22157

["Narrative 1 - 'I was working ZZZ and North arrival. I had been on position for about 20 minutes and there was weather on the scope when I sat down. I was briefed that there had been some deviations but just light chop. And area of heavy precipitation which had been west of ZZZ1 eventually moved onto the final but aircraft were still taking the approach and landing. Eventually we got some LLWS alerts which I issued which in short time were followed by several go arounds and a microburst alert which I also issued as well as described the precipitation along the final. Aircraft X said he needed to discontinue the approach so I issued a 220 heading and 5000 feet since departure was getting a go-around in front of him and I couldn't turn him left or right due to airspace constraints. I yelled to departure and shipped him. In the mean time every other aircraft on final clogged up the frequency saying they also wouldn't take the approach. At some point Aircraft X said that he encountered almost unrecoverable conditions and had climbed to nearly 8000 feet.We need to have a much better plan of action when there is weather in the area. Our current method of giving the approach until aircraft refuse to take it while informing them of the weather will only result in this kind of situation in the future; which I find unacceptable. There was already a ground delay program in place when this happened; but there were no miles in trail out and I was oversaturated with aircraft. In the future I will will make a bigger point to not run aircraft through a final that is heavy precipitation even if outside they are below the layer and willing to take it. Also I think pilots need to be more vocal about saying what they see outside because often times we have no way of knowing what the weather is really like outside.'",
 "Narrative 1 - 'Wheelchair battery form and procedures reviewed and completed. Ramp Agent gave me the form; only knew they had to sign it. Did not know where battery was or if steps followed. Battery in back. When asked how big it was; did not know for sheet. We found passenger and confirmed battery info. Passenger removed USB drive with cord/metal that could have completed connection to terminals. Batteries stored in a computer bag with no other items/secured. Two batteries at 158.4; under the 160 limit. FAs notified. FO notified.'",
 "Narrative 1 - 'The aircraft at some point in the past had a quick drain oil plug installed accessible via the nose gear well. This plug was safety wired to an angled piece of aluminum that was riveted to the drain plug cover plate that is secured to the airframe. These aftermarket STCed quick drains are made of aluminum. The aircraft recently came out of annual and had about 2.5 hours in service at the time of the event. During the annual all engine mounts were replaced. The oil was changed. And a visual inspection of the drain plug safety wire confirmed it was attached to the aluminum bracket in the nose gear portion of the airframe.Upon entering the pattern at ZZZ on a return flight from ZZZ1; it was observed that the engine oil pressure was at the lower limit at 30 PSI. After landing and while taxiing to the FBO it was observed that oil pressure dropped to 0 PSI. Engine temperature was normal and no anomalies were detected. Upon shutdown and exiting the aircraft engine oil was observed; of oil covering the entire undercarriage of the airframe from tip to tail. Oil dropped; puddled; and pooled under the aircraft. Upon further inspection it was discovered that the oil plug was missing. The hole in the aluminum bracket safety wire attachment point was worn through; negating the usefulness of the safety wire. The service shop at ZZZ replaced the plug with an original certificated plug and safety wired to the engine and NOT the airframe.It's believed that the failure of the drain plug to stay safely secured was caused by it being secured to the airframe; which with the engine running was able to vibrate its way loose. Further investigation revealed that it's a common practice to secure this aftermarket quick drain plug valve to the airframe because it extends through the access plate; making it convenient but not effective. In hindsight I'm glad we didn't drop the oil while climbing out over ZZZ2 in Day 0. Otherwise I might not have been able to write this. I hope this information is helpful and gets disseminated as soon as possible. I shared my experience with the service personnel that performed my annual. They had an A36 Bonanza in their shop also with the same drain plug secured to the airframe. Upon hearing about my experience they immediately removed the safety wire from the airframe and secured it to the engine.'",
 "Narrative 1 - 'My FO deadheaded into ZZZ and was aware first hand that there was a problem with the rudder pedals noted by the inbound crew. The inbound crew wrote it up and maintenance did their checks and were unable to duplicate the problem. After talking with the maintenance guy and he was running down the list of items they checked; I asked if they checked for a brake possibly dragging. He said he didn't notice anything unusual on his initial walk around; but went and checked anyway just to make sure to which he found no abnormalities. With everything looked at that the mechanic and I could think of and he couldn't find any problems; I determined the airplane was OK to fly unless it gave me a problem during the control checks; taxi or takeoff. After pushback; engine start and during my control check; I noted a significant amount of pressure was required to actuate the rudders and the left rudder required more pressure to actuate than the right. I wanted to make sure I wasn't being prejudiced by expecting a problem and asked my FO to actuate the rudders and tell me what he felt without telling him what I felt. After he did; he told me that he felt the same thing I did. After that; I called Dispatch and told my Dispatcher what happened and we agreed we needed to return to the gate which we did. Once we were in the gate; I called my Dispatcher back and talked to maintenance about what we experienced. After we put the problem in the logbook; the mechanic turned the electric hydraulic pumps on to do his checks and said the rudder pressure felt normal to him. That seemed wildly unusual considering what we experienced; so I asked him if I could actuate the rudders to see for myself. To my surprise; the pressure required to actuate the rudder peddles was normal. I told the mechanic that what we experienced was significantly different with the engines running than what we experienced with just the electric pumps. After that; we were released and sent to the hotel. Maintenance said there was a leaking rudder ratio module that was causing the abnormal rudder pedal pressure. We should all be critical of any abnormality with the airplane and investigate the problem thoroughly. My FO was solid and objective in his evaluation of the situation and came to the same determination as I did. If he had come up with a different conclusion; I would have listened to what he had to say to make sure I didn't overlook any details.'",
 "Narrative 1 - 'Upon reaching clearance for ILS XX circle Runway XY at ZZZ from Approach; we were switched over to ZZZ Tower frequency. Established on the approach between the IAF and FAF; I keyed the mic to establish contact with Tower inbound. The entire avionics turned off completely; losing intercom; transponder; GPS/Nav/Comm 1; and Nav/Comm 2. ZZZ was currently under IFR due to 2SM visibility; but we were in visual conditions on the approach course. I broke off from the approach and turned to the south; since we were no longer receiving navigational guidance along the approach; and I had no communications to contact Tower or Approach. I knew the weather towards the south was looking clearer so the plan was to continue south towards ZZZ1 or ZZZ2. We troubleshot the avionics; checking circuit breakers and cycling the avionics switch to no avail. No indications of ammeter discharge or low voltage illuminated; and the turn coordinator was still operable as well as engine instruments; so I presumed that the failure was based solely on avionics and not complete electrical failure. We descended lower; maintaining VFR so that we could receive cell signal; and I contacted ZZZ Tower via cellphone; since they gave us instructors their phone number another time when they had an ATC/instructor meeting. I told them we were okay; and had complete avionics failure. I asked for the phone number for ZZZ1 Tower so I could communicate with them if I decided to continue south to ZZZ1. At that time; the visibility and clouds around ZZZ began to clear up and we could start to see towards ZZZ. I asked ZZZ Tower if the field was still IFR; and they replied that it just went VFR. We proceeded inbound toward ZZZ; maintaining VFR; and were able to receive landing and taxi clearances for our aircraft through the cell phone. The aircraft was repaired; with the problem being a short-circuited avionics switch.'"]

In [ ]:
embeddings = model.encode(sentences)
np.save("all_rebalance_train_embeddings.npy", embeddings)

W0501 13:49:35.918000 15956 torch/_inductor/utils.py:1679] [1/0_1] Not enough SMs to use max_autotune_gemm mode

In [ ]:
embeddings.shape

(22157, 768)

##

# Load & Index Embeddings

In [9]:
!pip install faiss-gpu-cu12
# !pip install faiss-cpu

Collecting faiss-gpu-cu12
  Downloading faiss_gpu_cu12-1.14.1.post1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (13 kB)
Requirement already satisfied: numpy<3,>=2 in /usr/local/lib/python3.12/dist-packages (from faiss-gpu-cu12) (2.0.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from faiss-gpu-cu12) (26.1)
Requirement already satisfied: nvidia-cuda-runtime-cu12>=12.1.105 in /usr/local/lib/python3.12/dist-packages (from faiss-gpu-cu12) (12.8.90)
Requirement already satisfied: nvidia-cublas-cu12>=12.1.3.1 in /usr/local/lib/python3.12/dist-packages (from faiss-gpu-cu12) (12.8.4.1)
Downloading faiss_gpu_cu12-1.14.1.post1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (48.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.4/48.4 MB 15.0 MB/s eta 0:00:00
Installing collected packages: faiss-gpu-cu12
Successfully installed faiss-gpu-cu12-1.14.1.post1

In [11]:
embeddings = np.load('all_rebalance_train_embeddings.npy')

In [12]:
# Normalize to unit vectors
row_norms = np.linalg.norm(embeddings, axis=1, keepdims=True)
norm_embed = embeddings / row_norms
norm_embed.shape

(22157, 768)

In [15]:
train_df = grouped_ds_train.to_pandas().set_index('acn')
train_df.index = train_df.index.astype('int')
train_df['group'] = train_df['group'].map(id_to_group)
group_masks = train_df.groupby('group').indices

In [18]:
import faiss
import numpy as np

dimension = norm_embed.shape[1]
index = faiss.IndexFlatIP(dimension)
index.add(norm_embed.astype('float32'))

def search_rag(query_text, k=5):
    query_vector = model.encode([query_text], convert_to_numpy=True).astype('float32')

    distances, indices = index.search(query_vector, k)
    results = train_df.iloc[indices[0]]
    return results

In [29]:
def find_similar(query_vector, cat_k=2, min_similarity=0.7):
  """
  Use cat_k=-1 to include all categories (and get similarities)
  """
  results = []
  if cat_k == -1:
    lims, scores, indices = index.range_search(query_vector, thresh=min_similarity)

    i = 0
    for acn, row in train_df.iloc[indices].iterrows():
      results.append([acn, row['text'], row['group'], scores[i]])
      i += 1

    df= pd.DataFrame(results, columns=['acn', 'text', 'label', 'score'])
    return df.sort_values(by=['score'], ascending=False)


  for cat, mask in group_masks.items():
    selector = faiss.IDSelectorArray(mask.astype('int64'))
    params = faiss.SearchParameters(sel=selector)
    scores, indices = index.search(query_vector, cat_k, params=params)

    is_similar = scores[0] >= min_similarity
    relevant_indices = indices[0][is_similar]
    relevant_scores = scores[0][is_similar]

    if not any(is_similar):
      continue

    for idx, text in enumerate(train_df.iloc[relevant_indices]['text'].values):
      results.append([cat, text, relevant_scores[idx]])

  return pd.DataFrame(results, columns=['label', 'text', 'score'])

In [32]:
res = find_similar(np.array([norm_embed[24]]), cat_k=-1, )
res

,acn,text,label,score
0,2100261,Narrative 1 - 'The day started by working a la...,humanfactors,1.000000
3,1643427,Narrative 1 - 'At rotation the flight deck doo...,companypolicy,0.748866
1,1791930,Narrative 1 - 'During brief; maintenance write...,humanfactors,0.728330
4,1768223,Narrative 1 - 'On our third and final flight a...,humanfactors,0.708821
2,2233308,Narrative 1 - 'We received a forward entry doo...,aircraft,0.708697

In [20]:
grouped_ds_train[6]

{'acn': 1853327,
 'text': "Narrative 1 - 'While on ILS final to LAX Runway 25L at approximately 7 miles from Runway 25L and 2;000 feet AGL; LAX Tower cleared a B747 to take off in front of us on 25L. Both the Captain and I remarked that we were unhappy with the spacing and while it looked like the runway would be clear in time; we both remarked that we should be prepared to go-around. The Captain elected to fly slightly above the glide path to avoid turbulence; but at around 200 feet AGL we encountered moderate turbulence from the departing B747 lasting around 1-2 seconds. After exiting the turbulence I estimated we would touch down 2;000-2;500 feet down; and I said; 'We're going to be long.' The Captain made a smooth correction to glide path and a smooth touchdown probably around the 2;000 foot point. There were no GPWS warnings or 'long landing' warnings at any point. I don't know whether the Tower spacing between us and the B747 met standards; but I thought it was a poor decision to clear a B747 for takeoff in front of us with that spacing on the same runway.'",
 'label': 14,
 'group': 13}

In [21]:
res = find_similar(np.array([norm_embed[6]]), min_similarity=0.7, cat_k=1)
res

,label,text
0,environment-nonweatherrelated,Narrative 1 - 'After on speed; normal sink rat...
1,humanfactors,Narrative 1 - 'We were flying the ILS 27R to O...
2,procedure,Narrative 1 - 'While on ILS final to LAX Runwa...

In [ ]:
processed_to_unprocessed = {
    'airport': 'Airport',
    'airspacestructure': 'Airspace Structure',
    'atcequipment/navfacility/buildings': 'ATC Equipment / Nav Facility / Buildings',
    'chartorpublication': 'Chart or Publication',
    'companypolicy': 'Company Policy',
    'environment-nonweatherrelated': 'Environment - Non-weather Related',
    'equipment/tooling': 'Equipment / Tooling',
    'incorrect/notinstalled/unavailablepart': 'Incorrect / Not Installed / Unavailable Part',
    'logbookentry': 'Logbook Entry',
    'manuals': 'Manuals',
    'mel': 'MEL (Minimum Equipment List)',
    'softwareandautomation': 'Software and Automation',
    'staffing': 'Staffing'
}

template = """Prelabeled Incident: {text}
Existing Analyst Label: {label}
---
"""
def format_examples(df: pd.DataFrame):
  res = "\n"
  for idx, row in df.iterrows():
    res += template.format(text=row['text'], label=processed_to_unprocessed[row['label']])
  return res

print(format_examples(res))

Prelabeled Incident: Narrative 1 - 'On approach to [Runway] 34R at DEN and descending below 10;000; we had a total lost of our GPS signal.  We did not get it back the entire approach and landing. We notified ATC. We were on vectors to the ILS so it did not affect our flight. DEN ATC knew about the issue and were not issuing any clearances for RNAV approaches. Multiple aircraft were having the same issue. We also had an ADS-B reporting fault at the same time.'
Existing Analyst Label: Airspace Structure
---
Prelabeled Incident: Narrative 1 - 'Due to continued 5G interference in the DEN area we lost GPS-L; GPS-R; and got an XPNDER FAIL light turning over FFFAT on the LAWGR 3 arrival.  Later after capturing the localizer to 35R we could see the depicted path on the navigation display was offset from the actual localizer final approach course.  No further issue or anomaly was experienced.  Systems returned to normal by the time we parked at the gate.'
Existing Analyst Label: Airspace Structure
---
Prelabeled Incident: Narrative 1 - 'On departure on the SLEEK 2 RNAV Departure approximately at 7;000 feet turning toward KIDNG intersection lost GPS-L and then GPS-R momentarily.  Not sure what had caused it (maybe 5G).  Denver Departure was asking several questions to other aircraft about the loss of GPS.  After a few seconds GPS was functioning appropriately without any issues on the flight to ZZZ1.'
Existing Analyst Label: ATC Equipment / Nav Facility / Buildings
---
Prelabeled Incident: Narrative 1 - 'During the initial climb on the ZZZZZ2 RNAV departure off of runway XXL; we had a TAWS (Terrain Alert Warning) and a GPS lost warning. We also lost all GPS navigation guidance to the Autopilot. I took over by using the heading mode while informing ATC departure control that we had lost all GPS signal and requested Radar Vectors. I was given a Radar Vector to a heading of 140 degrees and instruction to remain clear of all obstructions. I also asked ATC if any other aircraft had experienced the same issue. The response was negative. Since; I had a second pilot; I instructed them to check the GPS integrity and satellite strength. While they were performing the task; I continued to fly the aircraft and communicate with ATC. After approximately three minutes after losing signal; we regained GPS signal and the second pilot confirmed system integrity. I subsequently informed ATC that we had regained GPS navigation ability and they eventually cleared us direct to a navigation fix and I reengaged the GPS navigation mode without any further problems to our destination.'
Existing Analyst Label: ATC Equipment / Nav Facility / Buildings
---
Prelabeled Incident: Narrative 1 - 'While on the LAWGR3 STAR into DEN; we heard two other aircraft report loss of GPS signal.  Then approximately after YUPEE we lost both of our GPS signals.  Our navigation accuracy slowly degraded; to the point we lost terrain displays while in IMC; which is a little concerning near the Rockies.  We regained the GPS signals outside and perpendicular to the DORRY waypoint on the ILS.  By that short time our RNP accuracy degraded from 0.03 to 0.31.  After regaining GPS coverage outside DORRY it quickly came back to 0.03 accuracy.  When cleared for the approach and inside of DORRY the GPS signal dropped again; but since we were established on the ILS was not a big concern.  Had we been on the RNP we would have been unable to accomplish the approach.  We heard another type aircraft report another anomaly and are guessing that this is a 5G interference issue; but not sure.'
Existing Analyst Label: Environment - Non-weather Related
---
Prelabeled Incident: Narrative 1 - 'Complete GPS loss of signal as we crossed the coast in point to RPLL. Signal was lost for remainder of flight. Also on takeoff from RPLL we had a complete loss of GPS signal until coast out. No notice on NOTAMs viewed. No notices on RPLL ATIS.'
Existing Analyst Label: Environment - Non-weather Related
---