# Setup

In [ ]:
import datasets
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import json
from google.colab import drive, userdata
from huggingface_hub import login, hf_hub_download
from pprint import pprint

cache_path = "/content/huggingface_cache"
os.makedirs(cache_path, exist_ok=True)
os.environ['HF_HOME'] = cache_path

if userdata.get('HF_TOKEN'):
  login(token=userdata.get('HF_TOKEN'))
  hf_hub_download(repo_id="sookiemonster/asrs-narratives", filename="utils.py", repo_type="dataset",local_dir=".")

utils.py: 0.00B [00:00, ?B/s]

## Preprocessing

In [ ]:
raw_dataset = datasets.load_dataset("sookiemonster/asrs-narratives")

train_ds = datasets.load_dataset("sookiemonster/asrs-narratives-rebalance", split='train')
valid_ds = raw_dataset['validation']
test_ds = raw_dataset['test']

labels = train_ds.features['label'].names

id_to_label = { idx : label for idx, label in enumerate(labels) }
label_to_id = { label : idx for idx, label in id_to_label.items() }

data/train-00000-of-00001.parquet:   0%|          | 0.00/22.8M [00:00<?, ?B/s]

data/validation-00000-of-00001.parquet:   0%|          | 0.00/4.09M [00:00<?, ?B/s]

data/test-00000-of-00001.parquet:   0%|          | 0.00/9.38M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/22992 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/4441 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/9868 [00:00<?, ? examples/s]

In [ ]:
from functools import partial

def filter_labels(ds, to_remove:list):
  to_remove_set = set(to_remove)
  return ds.filter(lambda example : id_to_label[example['label']] not in to_remove_set)

filter_ambiguous = partial(filter_labels, to_remove=['ambiguous'])

filtered_train_ds = filter_ambiguous(train_ds)
filtered_valid_ds = filter_ambiguous(valid_ds)
filtered_test_ds = filter_ambiguous(test_ds)

Filter:   0%|          | 0/22992 [00:00<?, ? examples/s]

Filter:   0%|          | 0/4441 [00:00<?, ? examples/s]

Filter:   0%|          | 0/9868 [00:00<?, ? examples/s]

In [ ]:
def _validate_groupings(groupings:dict[str, set]):
  mut_excl = [va.isdisjoint(vb) for ka, va in groupings.items() for kb, vb in groupings.items() if ka != kb]
  assert all(mut_excl), f"{mut_excl}"

  all_labels = set([label for val_set in groupings.values() for label in val_set])
  assert all_labels == set(id_to_label.values()), f"Missing: {set(id_to_label.values()) - all_labels}"


def group_labels(ds, groupings:dict[str, set]):
  _validate_groupings(groupings)
  group_names = list(groupings.keys())
  group_names.sort()

  fine_grained_label_to_group = {
      label : group_name for group_name, val_set in groupings.items() for label in val_set
  }

  res = ds.map(lambda ex: {"group" : fine_grained_label_to_group[ id_to_label[ex['label']] ]})
  res = res.filter(lambda ex: ex["group"] != 'DELETE')

  new_features = res.features.copy()
  group_names.remove("DELETE")
  new_features["group"] = ClassLabel(names=group_names)

  res = res.cast(new_features)
  return res

In [ ]:
def get_inv_class_weights(ds, labels, filter_by='group'):
  counts = ds.to_pandas()[filter_by].value_counts().to_dict()

  weights = {
      label : len(ds) / (len(labels) * counts[i]) for i, label in enumerate(labels) if counts.get(i, 0) > 0
  }

  tot = sum(weights.values())
  norm =  {
      k: round(v / tot, 4) for k,v in weights.items()
  }

  return norm

# Summarization (via Decoder)

In [ ]:
from datasets import ClassLabel

groupings = {
    'DELETE' : set(['ambiguous']),
}

groupings = groupings | {
    label : set([label]) for label in id_to_label.values() if label != 'ambiguous'
}

grouped_ds_train = group_labels(filtered_train_ds, groupings)
grouped_ds_valid = group_labels(filtered_valid_ds, groupings)
grouped_ds_test = group_labels(filtered_test_ds, groupings)

Map:   0%|          | 0/22157 [00:00<?, ? examples/s]

Filter:   0%|          | 0/22157 [00:00<?, ? examples/s]

Casting the dataset:   0%|          | 0/22157 [00:00<?, ? examples/s]

Map:   0%|          | 0/4083 [00:00<?, ? examples/s]

Filter:   0%|          | 0/4083 [00:00<?, ? examples/s]

Casting the dataset:   0%|          | 0/4083 [00:00<?, ? examples/s]

Map:   0%|          | 0/9072 [00:00<?, ? examples/s]

Filter:   0%|          | 0/9072 [00:00<?, ? examples/s]

Casting the dataset:   0%|          | 0/9072 [00:00<?, ? examples/s]

In [ ]:
id_to_group = { i: group for i, group in enumerate(grouped_ds_train.features['group'].names) }
id_to_group

{0: 'aircraft',
 1: 'airport',
 2: 'airspacestructure',
 3: 'atcequipment/navfacility/buildings',
 4: 'chartorpublication',
 5: 'companypolicy',
 6: 'environment-nonweatherrelated',
 7: 'equipment/tooling',
 8: 'humanfactors',
 9: 'incorrect/notinstalled/unavailablepart',
 10: 'logbookentry',
 11: 'manuals',
 12: 'mel',
 13: 'procedure',
 14: 'softwareandautomation',
 15: 'staffing',
 16: 'weather'}

In [ ]:
from pprint import pprint
pprint(grouped_ds_valid.to_pandas().set_index('acn').loc[[1962404, 1944918, 1902367, 2046198, 1917476]]['text'].to_list())

["Narrative 1 - 'Ramp Agent could not speak English. Did not understand the "
 'security check process. Second issue; Dry Ice loaded in the lower forward '
 'without notification. Only found out about the dry ice and its requirements '
 'when I read the paperwork. Ramp did not pass the message to dispatch or us. '
 'Thankfully no one was affected by the CO2. The ZZZZ ramp seems to be less '
 'professional than before. Things like this are happening more and more. '
 'Please correct. [This issue was caused by the] lack of adherence to '
 'procedures and not caring because there are no consequences. Suggestions: '
 "Follow the procedures.'",
 "Narrative 1 - 'Departing ZZZ I received notification late in the boarding/ "
 'loading process we were taking HAZMAT. Specifically Nuclear Medicine. I '
 'received the amended Release as I was reviewing an MEL. I then spoke to the '
 'Ramp Agents who loaded the HAZMAT. I never received a NOTAC. I think in my '
 'head after talking to the Ramp Agents and the Agent for the second Release I '
 'had full filled my requirements. During climb I realized I should have '
 'received and signed the NOTAC. We finished the flight uneventfully.Slow down '
 'when distracted by other issues such as MEL review. Maybe have the Agent use '
 "a checklist to ensure we receive all the required paperwork.'",
 "Narrative 1 - 'It was brought to my attention that Job Card #XXXXXXX and Job "
 'Card #YYYYYYY had their contents swapped and modified out in the field. I '
 'inducted both Job Cards as new tooling. Job Card #XXXXXXX recently came due '
 'for calibration so [it] was returned to the calibration shop. For this Job '
 'Card; this was the first calibration since it was newly inducted into the '
 'system. In the process of doing a visual inspection prior to sending it to '
 'the vendor; it was discovered that someone combined parts of this kit with '
 'the other Job Card mentioned above. Whoever did the swapping was unqualified '
 'and did not follow our Calibration SOP nor our General Maintenance Manual '
 'for tooling. What was on the box did not match what was in [the System]. In '
 'addition; when they changed items around; they left the Maintenance and '
 'Engineering # the same; which was classified as NON-DG; but a lithium '
 'battery pack was added to the contents. No documentation was done in the '
 'changing of these kits. I have researched and cannot find out WHO went into '
 '[the System] and changed the contents. Of course; the last person that made '
 'this kit serviceable was me and they left my name and number on the '
 'calibration of this kit. In my research I have found so many errors that I '
 'am unable to mention all of them.After the research I have done; I have '
 'SEVERAL MAJOR concerns:Lithium Batteries. We use Maintenance and Engineering '
 'numbers to alert the presence of lithium batteries; which make that specific '
 'tool DG. If someone is able to change kit contents and add batteries to a '
 'kit without changing the Maintenance and Engineering number; then lithium '
 'batteries will be put in the belly of aircraft. DG tooling has made it very '
 'difficult to move tooling around quickly. This has created an atmosphere '
 'where people are trying to skirt around making tools DG even when they have '
 'lithium batteries.The Tooling Department seems to be losing the control '
 'strings on the kit management of our tooling. There is no visibility on WHO '
 'can go into [the System] and modify kit contents. The control strings are '
 'being loosened at the same time that there is NO TRANSPARENCY! Still; there '
 'is a lack of understanding of the importance of proper procedures when it '
 'comes to tooling and test equipment. I am using my A&P License to verify and '
 'certify test equipment; just like base / line mechanics are signing off '
 'aircraft log books. DG is here to stay and we should not be trying to '
 'MANIPULATE batteries into kits. If a tester has to have a battery to operate '
 'then it is DG! END OF STORY![A suggestion is to provide] education on '
 'tooling and test equipment. It has to start with Management in Maintenance '
 'and the Inspection departments. Again; I think a yearly CBT for all of '
 'Maintenance and Inspection and Tooling departments. Giving them the '
 'awareness of what goes into the certification and calibration of aircraft '
 'tooling. Give the Tooling Department back their control and allow them to '
 "police who is able to modify kit contents.'",
 "Narrative 1 - 'There were two copies of the NOTAC on the flight deck. I know "
 'there was confusion about which copy was to be given to the Operations '
 'Agent. Apparently; an unsigned copy was returned to the Operations Agent. We '
 'were aware of the HAZMAT on board. NOTAC was not signed by Captain. Better '
 'quality control by the Crew and Operations Agent on required documentation; '
 "even when running behind schedule.'\n"
 "Narrative 2 - 'Captain misunderstood Operations Agent directions for NOTAC "
 "form and did not reference Company communication.Didn't sign NOTAC form. "
 "Need to research for relevant policies for non-standard events.'",
 "Narrative 1 - 'We did the appropriate paperwork and prepared to depart ZZZ "
 'for ZZZ1. Picked up our clearance and departed. At some point in the climb '
 'we became aware of an odor distinctly that of gasoline. After discussing the '
 'notable lack of HAZMAT paperwork and the implications of such an odor we '
 'made the decision to turn around. Re-briefed the approach and our plan; '
 'called ZZZ Center and requested direct to the IAF for the ILS which we then '
 'performed as normal. After arriving back at the airport we opened the cargo '
 'door to inspect the cargo and locate the culprit. Upon doing so we '
 'discovered a shipment of gas cans (Jerry Jugs) that had not been cleaned '
 'properly. We removed them; searched the rest of the load for anything else '
 'that we should have been notified of its presence; removed what we could '
 'find; and redid the weight and balance. Filed a new flight plan; and '
 'departed once more for ZZZ1. The rest of the flight went without incident. A '
 'company mandated return report was filed with the appropriate operational '
 "personnel.'\n"
 "Narrative 2 - 'I was the FO on Flight X. We arrived into ZZZ to get loaded. "
 'The Captain informed me we were picking up camera equipment that was a cargo '
 'charter. The ground crew loaded our plane and supplied the Captain where '
 'each [component] weight was located. He did a weight and balance and I '
 'checked his math and also agreed we were within CG. They did not supply us '
 "anything that showed Hazmat paperwork. However; I didn't know that at the "
 'time. I went and gathered the cones and when I went to grab the tail stand I '
 'noticed it was 1/2 inch off the ground which I have never seen. I notified '
 'the Captain on the aft weight being heavy and told him he should come look. '
 'He declined to come inspect the weight aft  that was weighing down the tail '
 'stand but he checked the paperwork and said we would be OK. I did notice '
 'some gas cans which I believed to be brand new at the rear of the cargo '
 'area. I also noticed numerous large propane tanks. At this point I assumed '
 'the Capt knew about it.As we departed and were climbing out I started '
 'smelling a strong odor of gasoline. We were still in a critical phase of '
 'flight climbing out on our departure procedure. ATC cleared us direct ZZZZZ '
 'once 6000 feet. As we climb through 6000 feet clear of all obstacles I '
 'entered direct ZZZZZ in the GPS and then told the Captain I smelled a very '
 'strong odor of gasoline. He explained he did as well. We kept climbing '
 'trying to decide what was the odor exactly. I told him about the cans and '
 'propane tanks and asked if he knew if we had Hazmat onboard. He explained he '
 'was not told or given any Hazmat paperwork. We turned the blowers off as I '
 'was getting light headed from the fumes. I told the Captain I felt it was '
 'urgent we return to ZZZ or land at the nearest airport ZZZ2 to check the '
 'safety of our load and determine the odor. After a brief discussion the '
 'Captain agreed and we made the decision to return to ZZZ because there we '
 'had a better way of inspecting and checking for paperwork. The Captain '
 'notified ATC we needed to turn back to ZZZ due to odor coming from our '
 'cargo. We did our descent approach checklist after picking up current '
 'weather and started our approach into ZZZ. We landed safely in ZZZ. I got '
 'out and put the tail stand in immediately. When the Captain exited the '
 'aircraft the plane fell on to the stand. I told the Captain I was not '
 'leaving in that airplane until we got the load figured out and the weight '
 'and Balance was corrected. We went through and found approximately 10 gas '
 'cans that contained some gasoline left inside; flares; ammunition; bear '
 'spray; 100 small propane tanks; and  8 large propane tanks. None of them '
 'were on the manifest we were given. We removed those items. The Captain got '
 'a flashlight and went through most of the entire load.  The Captain '
 'redistributed the weight making our plane safely within the CG limits. We '
 'left ZZZ without any Hazmat onboard to our knowledge and we were well within '
 'CG.I learned a valuable lesson in this. I will never assume the Captain '
 'knows what is inside the aircraft. When I ask a Captain to come look at the '
 'CG I will not start the flight until that Captain comes and we as a team can '
 'determine our aircraft is loaded how the loaders told us and we are not '
 'carrying Hazmat materials unaware to us. It was flooding rain. The Captain '
 'and I both trusted the plane was loaded the way and with the contents the '
 'loader told us. We were delayed in a few other places and allowed the '
 'pressure of getting the cargo to ZZZ3 and the fact we were pushing our time '
 'to rush us. Once the Captain and myself discovered all these discrepancies '
 'we both slowed down; ensured the load was legal. We notified Dispatch while '
 'flying back we would not be making it to ZZZ3 as planned. We both were not '
 'going to have enough hours and both of us were fatigued. Once we realized '
 'the issue we made the right decisions to make it safe. I learned a valuable '
 "lesson from this incident and the Captain explained he did as well.'"]

### Make Summary Dataset

In [ ]:
def get_df(ds):
  df = ds.to_pandas().set_index('acn')
  df.drop('label', inplace=True, axis=1)
  df.group = df.group.map(id_to_group)
  return df

train_df = get_df(grouped_ds_train)
valid_df = get_df(grouped_ds_valid)
test_df = get_df(grouped_ds_test)

In [ ]:
sys_prompt = 'You are an expert Aviation Safety Analyst  an expert aviation safety analyst and technical writer.'
_template = """

Task: Read the provided aviation safety report and generate a concise, objective synopsis.

Information Requirements:
Your synopsis should be a concise, chronological summary of the facts and critical chain of events leading to the incident, specifying WHAT happened and WHY.

As you construct your response, here are examples of problems you would include in your synopsis (if mentioned):
  - Environment & Infrastructure: Weather, non-weather hazards (wildlife, drones), airport surface (lighting, markings), or airspace design conflicts.
  - Technical & Systems: Aircraft mechanical failures, software/automation glitches (FMS, EFB), ATC facility equipment, or ground tooling.
  - Human & Execution: Cognitive human factors (fatigue, distraction, miscommunication), procedure/SOP non-compliance, or staffing shortages.
  - Policy & Documentation: Company management pressure, chart/manual errors, checklist omissions, or maintenance compliance (MEL, wrong parts, logbooks).

Be sure to detail WHAT specifically happened.
Do not use broad statements to describe the situation (e.g. do NOT say "an environment or infrastructure error." or "there was an issue with policy documentation.").

Constraints & Tone:
* Maintain a strictly objective and professional tone.
* Do not speculate, hallucinate, or introduce any outside information not explicitly stated in the source text.
* Keep the synopsis brief (2 to 5 sentences) and stick strictly to the facts.
* Use clear, standard aviation terminology. If an acronym is used, always use the entire phrase, never use the acronym.
* ALWAYS output the requested JSON, with the report number (as given to you) and the synopsis (which you generate yourself).
* NEVER include introductory or concluding conversational filler.

Return your answer using the following strictly valid JSON format:
{{
  "report_number": "<the report number, exactly as it appears>",
  "synopsis": "<the synopsis you generate>"
}}

Source Text:
REPORT NUMBER: {acn}
REPORT TEXT: {text}
"""

def prompt_template(acn, text):
  return _template.format(acn=acn, text=text)

def make_inference_message(row):
  prompt = prompt_template(acn=row.name, text=row['text'])

  messages = []
  messages.append({'role' : 'system', 'content' : sys_prompt})
  messages.append({'role' : 'user', 'content' : prompt})

  return messages

pprint(make_inference_message(valid_df.iloc[1]))

[{'content': 'You are an expert Aviation Safety Analyst  an expert aviation '
             'safety analyst and technical writer.',
  'role': 'system'},
 {'content': '\n'
             '\n'
             'Task: Read the provided aviation safety report and generate a '
             'concise, objective synopsis. \n'
             '\n'
             'Information Requirements:\n'
             'Your synopsis should be a concise, chronological summary of the '
             'facts and critical chain of events leading to the incident, '
             'specifying WHAT happened and WHY.\n'
             '\n'
             'As you construct your response, here are examples of problems '
             'you would include in your synopsis (if mentioned):\n'
             '  - Environment & Infrastructure: Weather, non-weather hazards '
             '(wildlife, drones), airport surface (lighting, markings), or '
             'airspace design conflicts.\n'
             '  - Technical & Systems: Aircraft mechanical failures, '
             'software/automation glitches (FMS, EFB), ATC facility equipment, '
             'or ground tooling.\n'
             '  - Human & Execution: Cognitive human factors (fatigue, '
             'distraction, miscommunication), procedure/SOP non-compliance, or '
             'staffing shortages.\n'
             '  - Policy & Documentation: Company management pressure, '
             'chart/manual errors, checklist omissions, or maintenance '
             'compliance (MEL, wrong parts, logbooks).\n'
             '\n'
             'Be sure to detail WHAT specifically happened.\n'
             'Do not use broad statements to describe the situation (e.g. do '
             'NOT say "an environment or infrastructure error." or "there was '
             'an issue with policy documentation.").\n'
             '\n'
             'Constraints & Tone:\n'
             '* Maintain a strictly objective and professional tone.\n'
             '* Do not speculate, hallucinate, or introduce any outside '
             'information not explicitly stated in the source text.\n'
             '* Keep the synopsis brief (2 to 5 sentences) and stick strictly '
             'to the facts.\n'
             '* Use clear, standard aviation terminology. If an acronym is '
             'used, always use the entire phrase, never use the acronym.\n'
             '* ALWAYS output the requested JSON, with the report number (as '
             'given to you) and the synopsis (which you generate yourself). \n'
             '* NEVER include introductory or concluding conversational '
             'filler.\n'
             '\n'
             'Return your answer using the following strictly valid JSON '
             'format:\n'
             '{\n'
             '  "report_number": "<the report number, exactly as it '
             'appears>",\n'
             '  "synopsis": "<the synopsis you generate>"\n'
             '}\n'
             '\n'
             'Source Text:\n'
             'REPORT NUMBER: 2185235\n'
             "REPORT TEXT: Narrative 1 - 'I just received my UAS a day ago "
             'and  decided to just hover it above my house to see how good it '
             'is. In the DJI fly app zones it provided me at first it showed I '
             'was outside the airspace so I believed I was ok to fly but was '
             'aware I was close. I believe due to poor internet connection my '
             'location may have not been 100% accurate which caused the me '
             'thinking I was ok. After downloading another app for more '
             'precise locations (autopylot) I was then aware I was actually '
             'inside the airspace near the edge. In the two flights I '
             'conducted on Day 0 did not fly the drone any further then above '
             'my house and only for a few minutes prior to my knowledge of the '
             'violation. My house is only about 100ft away from being outside '
             'the airspace so the confusion of being inside or out is hard to '
             'tell but I do take responsibility. In the future I now know I '
             'should check multiple applications to see where the airspace is '
             'as well as fly my drone in an area clearly marked as class G. I '
             'am new to UAS rules and this being my first week I am learning a '
             'lot and will do my best to avoid a situation such as this '
             "again.'\n",
  'role': 'user'}]

In [ ]:

from datasets import Dataset, DatasetDict, load_dataset, ClassLabel

def make_dataset(df:pd.DataFrame):
  res = pd.DataFrame(df.apply(lambda r : make_inference_message(r), axis=1), columns=['messages'])
  res['label'] = df.group
  res['text'] = df.text
  ds = Dataset.from_pandas(res)
  groups = sorted(list(df.group.unique()))
  ds = ds.cast_column("label", ClassLabel(names=groups))
  return ds

inference_train_ds = make_dataset(train_df)
inference_valid_ds = make_dataset(valid_df)
inference_test_ds = make_dataset(test_df)
inference_valid_ds

Casting the dataset:   0%|          | 0/22157 [00:00<?, ? examples/s]

Casting the dataset:   0%|          | 0/4083 [00:00<?, ? examples/s]

Casting the dataset:   0%|          | 0/9072 [00:00<?, ? examples/s]

Dataset({
    features: ['messages', 'label', 'text', 'acn'],
    num_rows: 4083
})

In [ ]:
ds_dict = DatasetDict({
    'train' : inference_train_ds,
    'validation' : inference_valid_ds,
    'test' : inference_test_ds,
})

In [ ]:
ds_dict.push_to_hub("sookiemonster/asrs-summarization")

Uploading the dataset shards:   0%|          | 0/1 [00:00<?, ? shards/s]

Creating parquet from Arrow format:   0%|          | 0/23 [00:00<?, ?ba/s]

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

                              :  68%|######7   | 33.5MB / 49.6MB

Uploading the dataset shards:   0%|          | 0/1 [00:00<?, ? shards/s]

Creating parquet from Arrow format:   0%|          | 0/5 [00:00<?, ?ba/s]

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

                              :  97%|#########6| 8.29MB / 8.55MB

Uploading the dataset shards:   0%|          | 0/1 [00:00<?, ? shards/s]

Creating parquet from Arrow format:   0%|          | 0/10 [00:00<?, ?ba/s]

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

                              :  87%|########6 | 16.9MB / 19.6MB

CommitInfo(commit_url='https://huggingface.co/datasets/sookiemonster/asrs-summarization/commit/dc0bea315b9a32b8cc169ea5d2fbe20459f51fa0', commit_message='Upload dataset', commit_description='', oid='dc0bea315b9a32b8cc169ea5d2fbe20459f51fa0', pr_url=None, repo_url=RepoUrl('https://huggingface.co/datasets/sookiemonster/asrs-summarization', endpoint='https://huggingface.co', repo_type='dataset', repo_id='sookiemonster/asrs-summarization'), pr_revision=None, pr_num=None)

### Load Dataset

In [ ]:
from datasets import load_dataset
repo_id = "sookiemonster/asrs-summarization"

raw_ds = load_dataset(repo_id)
train_ds = raw_ds['train']
train_df = train_ds.to_pandas().set_index('acn')

valid_ds = raw_ds['validation']
valid_df = valid_ds.to_pandas().set_index('acn')

In [ ]:
valid_ds[0]

{'messages': [{'content': 'You are an expert Aviation Safety Analyst  an expert aviation safety analyst and technical writer.',
   'role': 'system'},
  {'content': '\n\nTask: Read the provided aviation safety report and generate a concise, objective synopsis. \n\nInformation Requirements:\nYour synopsis should be a concise, chronological summary of the facts and critical chain of events leading to the incident, specifying WHAT happened and WHY.\n\nAs you construct your response, here are examples of problems you would include in your synopsis (if mentioned):\n  - Environment & Infrastructure: Weather, non-weather hazards (wildlife, drones), airport surface (lighting, markings), or airspace design conflicts.\n  - Technical & Systems: Aircraft mechanical failures, software/automation glitches (FMS, EFB), ATC facility equipment, or ground tooling.\n  - Human & Execution: Cognitive human factors (fatigue, distraction, miscommunication), procedure/SOP non-compliance, or staffing shortages.\n  - Policy & Documentation: Company management pressure, chart/manual errors, checklist omissions, or maintenance compliance (MEL, wrong parts, logbooks).\n\nBe sure to detail WHAT specifically happened.\nDo not use broad statements to describe the situation (e.g. do NOT say "an environment or infrastructure error." or "there was an issue with policy documentation.").\n\nConstraints & Tone:\n* Maintain a strictly objective and professional tone.\n* Do not speculate, hallucinate, or introduce any outside information not explicitly stated in the source text.\n* Keep the synopsis brief (2 to 5 sentences) and stick strictly to the facts.\n* Use clear, standard aviation terminology. If an acronym is used, always use the entire phrase, never use the acronym.\n* ALWAYS output the requested JSON, with the report number (as given to you) and the synopsis (which you generate yourself). \n* NEVER include introductory or concluding conversational filler.\n\nReturn your answer using the following strictly valid JSON format:\n{\n  "report_number": "<the report number, exactly as it appears>",\n  "synopsis": "<the synopsis you generate>"\n}\n\nSource Text:\nREPORT NUMBER: 2018769\nREPORT TEXT: Narrative 1 - \'Winds light and variable with occasional up and down drafts above runway. Student started to flare too early. Instructor pitched plane forward to keep approach speed decent angle until closer to the runway. Aircraft entered downdraft which made for large vertical descent rate. A go-around was initiated but aircraft touched down and struck the tail in the process. The aircraft touched down hard but no tail strike was felt by the pilots. [Was caused by] occasional up and down drafts and student flaring too early\'\n',
   'role': 'user'}],
 'label': 8,
 'text': "Narrative 1 - 'Winds light and variable with occasional up and down drafts above runway. Student started to flare too early. Instructor pitched plane forward to keep approach speed decent angle until closer to the runway. Aircraft entered downdraft which made for large vertical descent rate. A go-around was initiated but aircraft touched down and struck the tail in the process. The aircraft touched down hard but no tail strike was felt by the pilots. [Was caused by] occasional up and down drafts and student flaring too early'",
 'acn': 2018769}

### Inference

In [ ]:
import asyncio
from google.colab import userdata
from openai import AsyncOpenAI

model = "openai/gpt-oss-120b"
sem = asyncio.Semaphore(190) # DI only allows <200 concurrent per model

client = AsyncOpenAI(
    api_key=userdata.get("DEEPINFRA_TOKEN"),
    base_url="https://api.deepinfra.com/v1/openai",
)

async def ask_model(messages):
  async with sem:
    response = await client.chat.completions.create(
        model=model,
        messages=messages,
        prompt_cache_key='incident-report-analysis',
        reasoning_effort='low',
        response_format={"type": "json_object"},
    )
    return response

In [ ]:
small_train = train_ds.shuffle(seed=42).select(range(5000))
small_train.to_pandas()['label'].value_counts()

label
8     1269
13    1262
0      775
16     387
5      293
6      249
4      166
3      146
2      142
7       82
1       80
15      48
11      34
12      32
9       22
14      11
10       2
Name: count, dtype: int64

In [ ]:
# batch = list(small_train['messages'])
batch = list(valid_ds['messages'])
batch[0]

[{'content': 'You are an expert Aviation Safety Analyst  an expert aviation safety analyst and technical writer.',
  'role': 'system'},
 {'content': '\n\nTask: Read the provided aviation safety report and generate a concise, objective synopsis. \n\nInformation Requirements:\nYour synopsis should be a concise, chronological summary of the facts and critical chain of events leading to the incident, specifying WHAT happened and WHY.\n\nAs you construct your response, here are examples of problems you would include in your synopsis (if mentioned):\n  - Environment & Infrastructure: Weather, non-weather hazards (wildlife, drones), airport surface (lighting, markings), or airspace design conflicts.\n  - Technical & Systems: Aircraft mechanical failures, software/automation glitches (FMS, EFB), ATC facility equipment, or ground tooling.\n  - Human & Execution: Cognitive human factors (fatigue, distraction, miscommunication), procedure/SOP non-compliance, or staffing shortages.\n  - Policy & Documentation: Company management pressure, chart/manual errors, checklist omissions, or maintenance compliance (MEL, wrong parts, logbooks).\n\nBe sure to detail WHAT specifically happened.\nDo not use broad statements to describe the situation (e.g. do NOT say "an environment or infrastructure error." or "there was an issue with policy documentation.").\n\nConstraints & Tone:\n* Maintain a strictly objective and professional tone.\n* Do not speculate, hallucinate, or introduce any outside information not explicitly stated in the source text.\n* Keep the synopsis brief (2 to 5 sentences) and stick strictly to the facts.\n* Use clear, standard aviation terminology. If an acronym is used, always use the entire phrase, never use the acronym.\n* ALWAYS output the requested JSON, with the report number (as given to you) and the synopsis (which you generate yourself). \n* NEVER include introductory or concluding conversational filler.\n\nReturn your answer using the following strictly valid JSON format:\n{\n  "report_number": "<the report number, exactly as it appears>",\n  "synopsis": "<the synopsis you generate>"\n}\n\nSource Text:\nREPORT NUMBER: 2018769\nREPORT TEXT: Narrative 1 - \'Winds light and variable with occasional up and down drafts above runway. Student started to flare too early. Instructor pitched plane forward to keep approach speed decent angle until closer to the runway. Aircraft entered downdraft which made for large vertical descent rate. A go-around was initiated but aircraft touched down and struck the tail in the process. The aircraft touched down hard but no tail strike was felt by the pilots. [Was caused by] occasional up and down drafts and student flaring too early\'\n',
  'role': 'user'}]

In [ ]:
from tqdm.asyncio import tqdm_asyncio

tasks = [ask_model(p) for p in batch]
# results = await asyncio.gather(*tasks, return_exceptions=True)
results = await tqdm_asyncio.gather(*tasks)

100%|██████████| 4083/4083 [02:32<00:00, 26.69it/s]

In [ ]:
for entry in results:
  print(json.dumps(entry.to_dict(), indent=2))

{
  "id": "chatcmpl-R0WiOfeaitv45Kvr2PpbkNm7",
  "choices": [
    {
      "finish_reason": "stop",
      "index": 0,
      "logprobs": null,
      "message": {
        "content": "{\n  \"report_number\": \"2018769\",\n  \"synopsis\": \"During a student pilot landing, light variable winds with occasional updrafts and downdrafts over the runway caused the aircraft to encounter a downdraft, resulting in a rapid vertical descent. The student flared too early, and the flight instructor pushed the nose forward to maintain approach speed, but the downdraft increased the descent rate. A go\u2011around was commanded, yet the aircraft contacted the runway hard and the tail impacted the ground during the aborted landing.\"\n}",
        "role": "assistant",
        "tool_calls": [],
        "reasoning_content": "We need JSON. Report number 2018769. Synopsis 2-5 sentences. Include what happened and why: wind variable, dowdraft, early flare, instructor pitch, go-around, tail strike.",
        "name": null
      }
    }
  ],
  "created": 1778077179,
  "model": "openai/gpt-oss-120b",
  "object": "chat.completion",
  "usage": {
    "completion_tokens": 163,
    "prompt_tokens": 580,
    "total_tokens": 743,
    "prompt_tokens_details": null,
    "estimated_cost": 5.359000000000001e-05
  }
}
{
  "id": "chatcmpl-RUUPiXFMmzGcYkj3taHp1wYV",
  "choices": [
    {
      "finish_reason": "stop",
      "index": 0,
      "logprobs": null,
      "message": {
        "content": "{\n  \"report_number\": \"2185235\",\n  \"synopsis\": \"A newly acquired unmanned aircraft was flown near the operator's house while the pilot relied on the DJI fly application, which initially indicated the location was outside controlled airspace; poor internet connectivity resulted in inaccurate positioning, leading the pilot to mistakenly believe the flight was permitted. After consulting a second mapping application, the pilot realized the aircraft was actually inside controlled airspace near the boundary. The drone was hovered for only a few minutes before the violation was discovered, and the pilot acknowledges responsibility and the need to verify airspace status with multiple sources.\"\n}",
        "role": "assistant",
        "tool_calls": [],
        "reasoning_content": "We need JSON. Provide synopsis.",
        "name": null
      }
    }
  ],
  "created": 1778077178,
  "model": "openai/gpt-oss-120b",
  "object": "chat.completion",
  "usage": {
    "completion_tokens": 142,
    "prompt_tokens": 728,
    "total_tokens": 870,
    "prompt_tokens_details": null,
    "estimated_cost": 5.537200000000001e-05
  }
}

In [ ]:
# save[4]

{'id': 'chatcmpl-RfU59lgEnDUtKGGWVHnItQXo',
 'choices': [{'finish_reason': 'stop',
   'index': 0,
   'logprobs': None,
   'message': {'content': '{\n  "report_number": "1507597",\n  "synopsis": "The Jeppesen Professional navigation database flags a radiation warning area extending from CKH to PHNL, indicating that aircraft operating within this airspace at approximately 2800 feet above antenna systems could be exposed to direct radiation potentially causing harmful effects; the report requests clarification of the warning’s meaning and medical assessment of exposure levels and mitigation for flights inbound to Honolulu."\n}',
    'role': 'assistant',
    'tool_calls': [],
    'reasoning_content': "We need JSON. Report number 1507597. Synopsis: Jeppesen Professional shows a radiation warning area from CKH to PHNL at 2800 ft above antenna systems; flights in that corridor may be exposed to direct radiation. Operator requests interpretation and medical exposure info. That's it.",
    'name': None}}],
 'created': 1778015828,
 'model': 'openai/gpt-oss-120b',
 'object': 'chat.completion',
 'usage': {'completion_tokens': 158,
  'prompt_tokens': 585,
  'total_tokens': 743,
  'prompt_tokens_details': None,
  'estimated_cost': 5.2835e-05}}

In [ ]:
save = [res.to_dict() for res in results]

output_filename = "oss_120b_validation.json"
with open(output_filename, "w") as f:
  json.dump(save, f, indent=2)

### Load Inference Data

In [ ]:
output_filename = "oss_120b_validation.json"

raw_data = None
with open(output_filename, "r") as f:
  raw_data = json.load(f)

raw_data[0]

{'id': 'chatcmpl-RS1Bp1Ae8O42PDnMLIyGd8Jc',
 'choices': [{'finish_reason': 'stop',
   'index': 0,
   'logprobs': None,
   'message': {'content': '{\n  "report_number": "2018769",\n  "synopsis": "During a training landing, light variable wind with intermittent updrafts and downdrafts caused a sudden vertical descent when the student pilot flared prematurely. The flight instructor pushed the nose forward to maintain approach speed, but a downdraft increased the descent rate, leading the instructor to initiate a go‑around. The aircraft contacted the runway hard, and the tail impacted the ground during the attempted go‑around."\n}',
    'role': 'assistant',
    'tool_calls': [],
    'reasoning_content': 'We need JSON. Provide report number 2018769. Synopsis 2-5 sentences. Include what happened and why: variable wind, updraft/downdraft, student flared early, instructor intervened, aircraft encountered downdraft, large descent, go-around attempted but tail struck during hard touchdown. Provide concise.',
    'name': None}}],
 'created': 1778077325,
 'model': 'openai/gpt-oss-120b',
 'object': 'chat.completion',
 'usage': {'completion_tokens': 176,
  'prompt_tokens': 580,
  'total_tokens': 756,
  'prompt_tokens_details': None,
  'estimated_cost': 5.606e-05}}

In [ ]:
failed = []
def get_generation(result:dict) -> dict:
  try:
    text = result['choices'][0]['message']['content']
    text = json.loads(text)
    return text
  except json.JSONDecodeError:
    print("Failed to decode: ", result)
    failed.append(result)
    return {'report_number' : None, 'synopsis' : None}

def get_usage(result:dict) -> dict:
  return result['usage']

generations = [get_generation(pred) for pred in raw_data]
usages = [get_usage(pred) for pred in raw_data]

In [ ]:
print(len(failed))
# failed[5]['choices'][0]['message']

0

In [ ]:
synopses = pd.DataFrame(generations).rename({'report_number' : 'acn'}, axis=1).set_index('acn')
synopses = synopses.dropna(axis=0)
synopses.index = synopses.index.astype(int)
synopses

                                                  synopsis
acn
2018769  During a training landing, light variable wind...
2185235  A newly‑certified unmanned aircraft operator u...
2156158  During descent, the aircraft was using only th...
2139473  During climb out from ZZZ on a revenue flight ...
1813457  During boarding of flight ZZZ-ZZZ1, a fume eve...
...                                                    ...
2153249  Approximately 15 minutes after departure, an e...
1895387  Aircraft X arrived at ZZZ for a scheduled righ...
1939197  A drone was operated within 100 yards of the h...
2074236  During a visual approach to runway 24 at Birmi...
2057064  While taxiing toward Gate X, the aircraft enco...

[4083 rows x 1 columns]

In [ ]:
from datasets import Dataset, DatasetDict

def make_ds(split:str):
  df = None
  if split == 'train': df = train_df
  elif split == 'validation': df = valid_df
  else: raise "Not an allowed split!"

  joint = synopses.join(df, how='inner').drop(['text', 'messages'], axis=1)
  summary_ds = Dataset.from_pandas(joint)
  summary_ds = summary_ds.cast_column('label', train_ds.features['label'])
  return summary_ds

# summary_ds_valid = make_ds('train')
summary_ds_valid = make_ds('validation')

Casting the dataset:   0%|          | 0/4083 [00:00<?, ? examples/s]

In [ ]:
old = datasets.load_dataset('sookiemonster/asrs-summarization-classification')

README.md:   0%|          | 0.00/909 [00:00<?, ?B/s]

data/train-00000-of-00001.parquet:   0%|          | 0.00/1.70M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/4957 [00:00<?, ? examples/s]

In [ ]:
old['validation'] = summary_ds_valid

old

DatasetDict({
    train: Dataset({
        features: ['synopsis', 'label', 'acn'],
        num_rows: 4957
    })
    validation: Dataset({
        features: ['synopsis', 'label', 'acn'],
        num_rows: 4083
    })
})

In [ ]:
old.push_to_hub('sookiemonster/asrs-summarization-classification')

Uploading the dataset shards:   0%|          | 0/1 [00:00<?, ? shards/s]

Creating parquet from Arrow format:   0%|          | 0/5 [00:00<?, ?ba/s]

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

                              : 100%|##########| 1.70MB / 1.70MB

Uploading the dataset shards:   0%|          | 0/1 [00:00<?, ? shards/s]

Creating parquet from Arrow format:   0%|          | 0/5 [00:00<?, ?ba/s]

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

                              :  39%|###8      |  526kB / 1.36MB

CommitInfo(commit_url='https://huggingface.co/datasets/sookiemonster/asrs-summarization-classification/commit/3de389fae0900647534c96ef4160790312803dac', commit_message='Upload dataset', commit_description='', oid='3de389fae0900647534c96ef4160790312803dac', pr_url=None, repo_url=RepoUrl('https://huggingface.co/datasets/sookiemonster/asrs-summarization-classification', endpoint='https://huggingface.co', repo_type='dataset', repo_id='sookiemonster/asrs-summarization-classification'), pr_revision=None, pr_num=None)

# ModernBERT

In [ ]:
import datasets

raw_ds = datasets.load_dataset('sookiemonster/asrs-summarization-classification')
labels = raw_ds['train'].features['label'].names
id2label = { idx : label for idx, label in enumerate(labels)}
label2id = { label:idx for idx, label in enumerate(labels)}
raw_ds

README.md: 0.00B [00:00, ?B/s]

data/train-00000-of-00001.parquet:   0%|          | 0.00/1.70M [00:00<?, ?B/s]

data/validation-00000-of-00001.parquet:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/4957 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/4083 [00:00<?, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['synopsis', 'label', 'acn'],
        num_rows: 4957
    })
    validation: Dataset({
        features: ['synopsis', 'label', 'acn'],
        num_rows: 4083
    })
})

In [ ]:
# small_ds = raw_ds['train'].train_test_split(test_size=0.4, seed=42)
train_ds = raw_ds['train']
valid_ds = raw_ds['validation']

### Find Balanced Class Weights

In [ ]:
def get_inv_class_weights(labels, temp=1.0):
  unique, counts = np.unique(labels, return_counts=True)
  weights = (1 / counts) ** (1/temp)
  return np.round(weights / sum(weights), 3)

In [ ]:
weights = get_inv_class_weights(train_ds['label'], temp=4.0)

li = []
for idx, label in enumerate(labels):
  li.append([label, weights[idx]])

display(pd.DataFrame(li))
print(weights)

                                         0      1
0                                 aircraft  0.033
1                                  airport  0.057
2                        airspacestructure  0.050
3       atcequipment/navfacility/buildings  0.049
4                       chartorpublication  0.048
5                            companypolicy  0.042
6            environment-nonweatherrelated  0.043
7                        equipment/tooling  0.057
8                             humanfactors  0.029
9   incorrect/notinstalled/unavailablepart  0.080
10                            logbookentry  0.144
11                                 manuals  0.071
12                                     mel  0.072
13                               procedure  0.029
14                   softwareandautomation  0.094
15                                staffing  0.065
16                                 weather  0.039

[0.033 0.057 0.05  0.049 0.048 0.042 0.043 0.057 0.029 0.08  0.144 0.071
 0.072 0.029 0.094 0.065 0.039]

In [ ]:
sum(list([float(w) for w in weights]))

1.002

In [ ]:
list([float(w) for w in weights])

[0.033,
 0.057,
 0.05,
 0.049,
 0.048,
 0.042,
 0.043,
 0.057,
 0.029,
 0.08,
 0.144,
 0.071,
 0.072,
 0.029,
 0.094,
 0.065,
 0.039]

In [ ]:
weights = get_inv_class_weights(train_ds['label'], temp=2.0)

li = []
for idx, label in enumerate(labels):
  li.append([label, weights[idx]])

display(pd.DataFrame(li))
# print(weights)
print(sum(list([float(w) for w in weights])))
print(list([float(w) for w in weights]))

                                         0      1
0                                 aircraft  0.015
1                                  airport  0.046
2                        airspacestructure  0.034
3       atcequipment/navfacility/buildings  0.034
4                       chartorpublication  0.032
5                            companypolicy  0.024
6            environment-nonweatherrelated  0.026
7                        equipment/tooling  0.045
8                             humanfactors  0.011
9   incorrect/notinstalled/unavailablepart  0.089
10                            logbookentry  0.288
11                                 manuals  0.070
12                                     mel  0.072
13                               procedure  0.012
14                   softwareandautomation  0.123
15                                staffing  0.059
16                                 weather  0.021

1.001
[0.015, 0.046, 0.034, 0.034, 0.032, 0.024, 0.026, 0.045, 0.011, 0.089, 0.288, 0.07, 0.072, 0.012, 0.123, 0.059, 0.021]

### Tuning

In [ ]:
import torch
import sys

print(f"Python Version: {sys.version_info.major}.{sys.version_info.minor}")
print(f"PyTorch Version: {torch.__version__.split('+')[0]}")
print(f"CUDA Version (Torch): {torch.version.cuda}")
print(f"CXX11 ABI: {torch._C._GLIBCXX_USE_CXX11_ABI}")

Python Version: 3.12
PyTorch Version: 2.10.0
CUDA Version (Torch): 12.8
CXX11 ABI: True

In [ ]:
!pip install "https://github.com/lesj0610/flash-attention/releases/download/v2.8.3-cu12-torch2.10-cp312/flash_attn-2.8.3%2Bcu12torch2.10cxx11abiTRUE-cp312-cp312-linux_x86_64.whl"

Collecting flash-attn==2.8.3+cu12torch2.10cxx11abiTRUE
  Downloading https://github.com/lesj0610/flash-attention/releases/download/v2.8.3-cu12-torch2.10-cp312/flash_attn-2.8.3%2Bcu12torch2.10cxx11abiTRUE-cp312-cp312-linux_x86_64.whl (253.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 253.6/253.6 MB 4.9 MB/s eta 0:00:00
Requirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (from flash-attn==2.8.3+cu12torch2.10cxx11abiTRUE) (2.10.0+cu128)
Requirement already satisfied: einops in /usr/local/lib/python3.12/dist-packages (from flash-attn==2.8.3+cu12torch2.10cxx11abiTRUE) (0.8.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch->flash-attn==2.8.3+cu12torch2.10cxx11abiTRUE) (3.29.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch->flash-attn==2.8.3+cu12torch2.10cxx11abiTRUE) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch->flash-attn==2.8.3+cu12torch2.10cxx11abiTRUE) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch->flash-attn==2.8.3+cu12torch2.10cxx11abiTRUE) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch->flash-attn==2.8.3+cu12torch2.10cxx11abiTRUE) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch->flash-attn==2.8.3+cu12torch2.10cxx11abiTRUE) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch->flash-attn==2.8.3+cu12torch2.10cxx11abiTRUE) (2025.3.0)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch->flash-attn==2.8.3+cu12torch2.10cxx11abiTRUE) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch->flash-attn==2.8.3+cu12torch2.10cxx11abiTRUE) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch->flash-attn==2.8.3+cu12torch2.10cxx11abiTRUE) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch->flash-attn==2.8.3+cu12torch2.10cxx11abiTRUE) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch->flash-attn==2.8.3+cu12torch2.10cxx11abiTRUE) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch->flash-attn==2.8.3+cu12torch2.10cxx11abiTRUE) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch->flash-attn==2.8.3+cu12torch2.10cxx11abiTRUE) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch->flash-attn==2.8.3+cu12torch2.10cxx11abiTRUE) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch->flash-attn==2.8.3+cu12torch2.10cxx11abiTRUE) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch->flash-attn==2.8.3+cu12torch2.10cxx11abiTRUE) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch->flash-attn==2.8.3+cu12torch2.10cxx11abiTRUE) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch->flash-attn==2.8.3+cu12torch2.10cxx11abiTRUE) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch->flash-attn==2.8.3+cu12torch2.10cxx11abiTRUE) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch->flash-attn==2.8.3+cu12torch2.10cxx11abiTRUE) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch->flash-attn==2.8.3+cu12torch2.10cxx11abiTRUE) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch->flash-attn==2.8.3+cu12torch2.10cxx11abiTRUE) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch->flash-attn==2.8.3+cu12torch2.10cxx11abiTRUE) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch->flash-attn==2.8.3+cu12torch2.10cxx11abiTRUE) (1.5.3)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch->flash-attn==2.8.3+cu12torch2.10cxx11abiTRUE) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch->flash-attn==2.8.3+cu12torch2.10cxx11abiTRUE) (3.0.3)
Installing collected packages: flash-attn
Successfully installed flash-attn-2.8.3

In [ ]:
!pip install evaluate

Collecting evaluate
  Downloading evaluate-0.4.6-py3-none-any.whl.metadata (9.5 kB)
Requirement already satisfied: datasets>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (4.0.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.0.2)
Requirement already satisfied: dill in /usr/local/lib/python3.12/dist-packages (from evaluate) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.2.2)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.32.4)
Requirement already satisfied: tqdm>=4.62.1 in /usr/local/lib/python3.12/dist-packages (from evaluate) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from evaluate) (3.6.0)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.12/dist-packages (from evaluate) (0.70.16)
Requirement already satisfied: fsspec>=2021.05.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (2025.3.0)
Requirement already satisfied: huggingface-hub>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (1.11.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from evaluate) (26.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (3.29.0)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (18.1.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (3.13.5)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (0.28.1)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (0.24.2)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (3.13)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (2026.4.22)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2026.1)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.23.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.7.0->evaluate) (4.13.0)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.7.0->evaluate) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.7.0->evaluate) (0.16.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->evaluate) (1.17.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.7.0->evaluate) (8.3.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.7.0->evaluate) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.7.0->evaluate) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.7.0->evaluate) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub>=0.7.0->evaluate) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub>=0.7.0->evaluate) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub>=0.7.0->evaluate) (0.1.2)
Downloading evaluate-0.4.6-py3-none-any.whl (84 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 7.2 MB/s eta 0:00:00
Installing collected packages: evaluate
Successfully installed evaluate-0.4.6

In [ ]:
import evaluate
from sklearn.metrics import classification_report, confusion_matrix


accuracy = evaluate.load("accuracy")
precison = evaluate.load("precision")
recall = evaluate.load("recall")

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=-1)

    print(classification_report(labels, predictions))

    return {
        "accuracy": accuracy.compute(predictions=predictions, references=labels)["accuracy"],
        "precision_macro": precison.compute(predictions=predictions, references=labels, zero_division=np.nan, average="macro")["precision"],
        "recall_macro": recall.compute(predictions=predictions, references=labels, average="macro")["recall"]
    }

Downloading builder script: 0.00B [00:00, ?B/s]

Downloading builder script: 0.00B [00:00, ?B/s]

Downloading builder script: 0.00B [00:00, ?B/s]

In [ ]:
from transformers import Trainer
import torch.nn as nn

class WeightedLossTrainer(Trainer):
    def __init__(self, *args, class_weights=None, **kwargs):
        super().__init__(*args, **kwargs)
        self.class_weights = torch.tensor(class_weights, dtype=torch.float32, device="cuda")
        self.loss_fct = nn.CrossEntropyLoss(weight=self.class_weights.to(torch.device("cuda")))

    def compute_loss(self, model, inputs, return_outputs=False, num_items_in_batch=None):
        labels = inputs.pop("labels")

        outputs = model(**inputs)
        logits = outputs.get("logits")

        loss = self.loss_fct(logits.view(-1, self.model.config.num_labels), labels.view(-1))

        return (loss, outputs) if return_outputs else loss

In [ ]:
from transformers import AutoTokenizer

MODEL_ID = "nomic-ai/modernbert-embed-base"
tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)

def preprocess(ds:datasets):
    PREFIX = "classification: "
    res = ds.remove_columns(["acn"]).rename_column('synopsis', 'text')
    res = res.map(lambda examples : {"text" : PREFIX + examples["text"]})
    res = res.map(lambda examples : tokenizer(
        examples["text"],
        padding=True,
        return_tensors="pt"
    ), batched=True)
    res = res.remove_columns(['text'])
    return res

tokenized_train = preprocess(train_ds)
tokenized_eval = preprocess(valid_ds)

config.json: 0.00B [00:00, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/694 [00:00<?, ?B/s]

Map:   0%|          | 0/4957 [00:00<?, ? examples/s]

Map:   0%|          | 0/4957 [00:00<?, ? examples/s]

Map:   0%|          | 0/4083 [00:00<?, ? examples/s]

Map:   0%|          | 0/4083 [00:00<?, ? examples/s]

In [ ]:
from transformers import AutoModelForSequenceClassification, DataCollatorWithPadding
import torch

model = AutoModelForSequenceClassification.from_pretrained(
    MODEL_ID,
    id2label=id2label,
    label2id=label2id,
    dtype=torch.bfloat16,
    num_labels=len(id2label),
)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = model.to(device=device)

model.safetensors:   0%|          | 0.00/596M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/134 [00:00<?, ?it/s]

ModernBertForSequenceClassification LOAD REPORT from: nomic-ai/modernbert-embed-base
Key               | Status  |
------------------+---------+-
classifier.weight | MISSING |
classifier.bias   | MISSING |
head.norm.weight  | MISSING |
head.dense.weight | MISSING |

Notes:
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [ ]:
from transformers import TrainingArguments, Trainer

# Adjusted to sum to 1
# TEMP: 4.0
# class_weights = [0.034,
#  0.058,
#  0.052,
#  0.049,
#  0.047,
#  0.041,
#  0.045,
#  0.061,
#  0.029,
#  0.077,
#  0.128,
#  0.075,
#  0.076,
#  0.029,
#  0.094,
#  0.066,
#  0.039]

# TEMP 2.0
class_weights = [0.015, 0.046, 0.034, 0.034, 0.032, 0.024, 0.026, 0.045, 0.011, 0.089, 0.288, 0.07, 0.072, 0.012, 0.123, 0.059, 0.021]

args = TrainingArguments(
    output_dir="./modernbert-finetuned",
    bf16=True,

    learning_rate=3e-5,
    lr_scheduler_type="cosine_with_restarts",
    lr_scheduler_kwargs={"num_cycles":4},
    num_train_epochs=15,
    weight_decay=0.01,

    per_device_train_batch_size=512,
    gradient_accumulation_steps=1,
    gradient_checkpointing=True,

    eval_strategy="epoch",
    save_strategy="epoch",
    push_to_hub=True,
    hub_model_id="sookiemonster/asrs-modernbert-summary-classifier-cosine-restarts",

    report_to="none",
    logging_steps=50,
)

trainer = WeightedLossTrainer(
    model=model,
    args=args,
    train_dataset=tokenized_train,
    eval_dataset=tokenized_eval,
    processing_class=tokenizer,
    compute_metrics=compute_metrics,
    class_weights=class_weights,
)

In [ ]:
# Cosine w/ 4-cycles -- num epochs 15 -- LR 3e-5
# Train on 5_000 train & eval on full validation
# Temp 2.0
trainer.train()

              precision    recall  f1-score   support

           0       0.88      0.78      0.83      1489
           1       0.56      0.45      0.50       110
           2       0.10      0.59      0.17        58
           3       0.26      0.65      0.37        57
           4       0.37      0.66      0.47        61
           5       0.05      0.17      0.08        24
           6       0.19      0.36      0.25       107
           7       0.23      0.53      0.32        17
           8       0.76      0.45      0.56      1517
           9       0.00      0.00      0.00         9
          10       0.00      0.00      0.00         1
          11       0.06      1.00      0.11         4
          12       0.11      0.09      0.10        11
          13       0.26      0.28      0.27       435
          14       0.07      0.03      0.04        30
          15       0.11      0.80      0.19         5
          16       0.48      0.83      0.61       148

    accuracy                           0.57      4083
   macro avg       0.26      0.45      0.29      4083
weighted avg       0.68      0.57      0.60      4083

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

              precision    recall  f1-score   support

           0       0.85      0.84      0.84      1489
           1       0.49      0.49      0.49       110
           2       0.20      0.33      0.25        58
           3       0.30      0.67      0.42        57
           4       0.40      0.66      0.50        61
           5       0.04      0.21      0.07        24
           6       0.20      0.29      0.24       107
           7       0.19      0.65      0.30        17
           8       0.75      0.58      0.65      1517
           9       0.22      0.67      0.33         9
          10       0.00      0.00      0.00         1
          11       0.20      0.25      0.22         4
          12       0.06      0.18      0.10        11
          13       0.27      0.24      0.25       435
          14       0.00      0.00      0.00        30
          15       0.06      0.20      0.10         5
          16       0.56      0.76      0.64       148

    accuracy                           0.62      4083
   macro avg       0.28      0.41      0.32      4083
weighted avg       0.67      0.62      0.64      4083

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

              precision    recall  f1-score   support

           0       0.87      0.82      0.84      1489
           1       0.50      0.46      0.48       110
           2       0.19      0.38      0.25        58
           3       0.30      0.61      0.41        57
           4       0.42      0.59      0.49        61
           5       0.04      0.17      0.06        24
           6       0.19      0.34      0.24       107
           7       0.24      0.59      0.34        17
           8       0.74      0.57      0.65      1517
           9       0.20      0.67      0.31         9
          10       0.00      0.00      0.00         1
          11       0.18      0.50      0.27         4
          12       0.04      0.09      0.05        11
          13       0.27      0.28      0.28       435
          14       0.00      0.00      0.00        30
          15       0.10      0.40      0.16         5
          16       0.55      0.79      0.65       148

    accuracy                           0.62      4083
   macro avg       0.28      0.43      0.32      4083
weighted avg       0.68      0.62      0.64      4083

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

              precision    recall  f1-score   support

           0       0.90      0.75      0.82      1489
           1       0.51      0.51      0.51       110
           2       0.14      0.43      0.21        58
           3       0.20      0.79      0.32        57
           4       0.54      0.46      0.50        61
           5       0.08      0.12      0.10        24
           6       0.38      0.14      0.20       107
           7       0.17      0.82      0.28        17
           8       0.72      0.65      0.68      1517
           9       0.21      0.33      0.26         9
          10       0.00      0.00      0.00         1
          11       0.10      0.75      0.18         4
          12       0.03      0.09      0.05        11
          13       0.31      0.20      0.25       435
          14       0.00      0.00      0.00        30
          15       0.09      0.60      0.15         5
          16       0.39      0.88      0.54       148

    accuracy                           0.62      4083
   macro avg       0.28      0.44      0.30      4083
weighted avg       0.68      0.62      0.63      4083

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

              precision    recall  f1-score   support

           0       0.85      0.84      0.84      1489
           1       0.47      0.45      0.46       110
           2       0.19      0.33      0.24        58
           3       0.32      0.51      0.39        57
           4       0.34      0.74      0.47        61
           5       0.04      0.25      0.07        24
           6       0.19      0.44      0.26       107
           7       0.24      0.59      0.34        17
           8       0.76      0.51      0.61      1517
           9       0.36      0.56      0.43         9
          10       0.00      0.00      0.00         1
          11       0.22      0.50      0.31         4
          12       0.09      0.18      0.12        11
          13       0.27      0.30      0.28       435
          14       0.00      0.00      0.00        30
          15       0.05      0.20      0.08         5
          16       0.62      0.75      0.68       148

    accuracy                           0.61      4083
   macro avg       0.29      0.42      0.33      4083
weighted avg       0.68      0.61      0.63      4083

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

              precision    recall  f1-score   support

           0       0.88      0.81      0.84      1489
           1       0.49      0.54      0.51       110
           2       0.14      0.38      0.20        58
           3       0.27      0.67      0.39        57
           4       0.48      0.49      0.49        61
           5       0.04      0.12      0.06        24
           6       0.24      0.30      0.26       107
           7       0.20      0.59      0.30        17
           8       0.75      0.57      0.65      1517
           9       0.16      0.78      0.27         9
          10       0.00      0.00      0.00         1
          11       0.25      0.75      0.38         4
          12       0.09      0.27      0.14        11
          13       0.28      0.29      0.28       435
          14       0.20      0.03      0.06        30
          15       0.08      0.40      0.13         5
          16       0.49      0.83      0.62       148

    accuracy                           0.62      4083
   macro avg       0.30      0.46      0.33      4083
weighted avg       0.68      0.62      0.64      4083

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

              precision    recall  f1-score   support

           0       0.88      0.81      0.84      1489
           1       0.50      0.46      0.48       110
           2       0.17      0.36      0.23        58
           3       0.26      0.68      0.38        57
           4       0.47      0.56      0.51        61
           5       0.03      0.08      0.04        24
           6       0.21      0.31      0.25       107
           7       0.18      0.59      0.28        17
           8       0.75      0.57      0.65      1517
           9       0.21      0.78      0.33         9
          10       0.00      0.00      0.00         1
          11       0.22      1.00      0.36         4
          12       0.07      0.18      0.10        11
          13       0.27      0.30      0.28       435
          14       0.17      0.03      0.06        30
          15       0.12      0.60      0.19         5
          16       0.50      0.84      0.62       148

    accuracy                           0.62      4083
   macro avg       0.29      0.48      0.33      4083
weighted avg       0.68      0.62      0.64      4083

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

              precision    recall  f1-score   support

           0       0.88      0.80      0.84      1489
           1       0.52      0.45      0.48       110
           2       0.14      0.34      0.20        58
           3       0.38      0.46      0.41        57
           4       0.37      0.72      0.49        61
           5       0.04      0.25      0.07        24
           6       0.25      0.39      0.30       107
           7       0.21      0.47      0.29        17
           8       0.75      0.54      0.62      1517
           9       0.40      0.22      0.29         9
          10       0.00      0.00      0.00         1
          11       0.17      0.75      0.27         4
          12       0.11      0.09      0.10        11
          13       0.24      0.35      0.29       435
          14       0.18      0.07      0.10        30
          15       0.07      0.40      0.12         5
          16       0.67      0.68      0.68       148

    accuracy                           0.60      4083
   macro avg       0.32      0.41      0.33      4083
weighted avg       0.68      0.60      0.63      4083

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

              precision    recall  f1-score   support

           0       0.88      0.79      0.83      1489
           1       0.50      0.52      0.51       110
           2       0.14      0.34      0.20        58
           3       0.24      0.72      0.36        57
           4       0.55      0.48      0.51        61
           5       0.01      0.04      0.02        24
           6       0.23      0.29      0.26       107
           7       0.20      0.59      0.30        17
           8       0.74      0.62      0.67      1517
           9       0.24      0.56      0.33         9
          10       0.00      0.00      0.00         1
          11       0.20      1.00      0.33         4
          12       0.08      0.27      0.12        11
          13       0.30      0.26      0.28       435
          14       0.17      0.03      0.06        30
          15       0.17      0.60      0.26         5
          16       0.49      0.84      0.62       148

    accuracy                           0.63      4083
   macro avg       0.30      0.47      0.33      4083
weighted avg       0.68      0.63      0.65      4083

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

              precision    recall  f1-score   support

           0       0.87      0.82      0.84      1489
           1       0.48      0.45      0.47       110
           2       0.15      0.34      0.21        58
           3       0.30      0.61      0.40        57
           4       0.42      0.66      0.51        61
           5       0.06      0.25      0.10        24
           6       0.21      0.38      0.27       107
           7       0.17      0.59      0.27        17
           8       0.75      0.57      0.65      1517
           9       0.22      0.67      0.33         9
          10       0.00      0.00      0.00         1
          11       0.20      1.00      0.33         4
          12       0.06      0.18      0.10        11
          13       0.26      0.26      0.26       435
          14       0.12      0.03      0.05        30
          15       0.10      0.60      0.17         5
          16       0.56      0.78      0.65       148

    accuracy                           0.62      4083
   macro avg       0.29      0.48      0.33      4083
weighted avg       0.68      0.62      0.64      4083

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

              precision    recall  f1-score   support

           0       0.88      0.81      0.84      1489
           1       0.49      0.45      0.47       110
           2       0.14      0.34      0.20        58
           3       0.33      0.61      0.43        57
           4       0.44      0.67      0.53        61
           5       0.04      0.12      0.06        24
           6       0.20      0.39      0.27       107
           7       0.16      0.59      0.26        17
           8       0.75      0.57      0.65      1517
           9       0.24      0.67      0.35         9
          10       0.00      0.00      0.00         1
          11       0.21      1.00      0.35         4
          12       0.06      0.18      0.09        11
          13       0.26      0.27      0.26       435
          14       0.12      0.03      0.05        30
          15       0.10      0.60      0.17         5
          16       0.55      0.80      0.65       148

    accuracy                           0.62      4083
   macro avg       0.29      0.48      0.33      4083
weighted avg       0.68      0.62      0.64      4083

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

              precision    recall  f1-score   support

           0       0.86      0.81      0.84      1489
           1       0.36      0.55      0.44       110
           2       0.11      0.38      0.17        58
           3       0.21      0.74      0.33        57
           4       0.57      0.51      0.54        61
           5       0.05      0.17      0.08        24
           6       0.31      0.20      0.24       107
           7       0.16      0.59      0.25        17
           8       0.75      0.54      0.63      1517
           9       0.25      0.22      0.24         9
          10       0.00      0.00      0.00         1
          11       0.15      1.00      0.27         4
          12       0.10      0.18      0.13        11
          13       0.28      0.25      0.26       435
          14       0.13      0.13      0.13        30
          15       0.07      0.20      0.11         5
          16       0.46      0.86      0.60       148

    accuracy                           0.60      4083
   macro avg       0.28      0.43      0.31      4083
weighted avg       0.67      0.60      0.62      4083

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

              precision    recall  f1-score   support

           0       0.88      0.80      0.84      1489
           1       0.51      0.44      0.47       110
           2       0.16      0.34      0.21        58
           3       0.33      0.61      0.43        57
           4       0.39      0.70      0.50        61
           5       0.04      0.25      0.08        24
           6       0.28      0.33      0.30       107
           7       0.16      0.59      0.26        17
           8       0.73      0.62      0.67      1517
           9       0.24      0.44      0.31         9
          10       0.00      0.00      0.00         1
          11       0.12      0.75      0.20         4
          12       0.07      0.18      0.11        11
          13       0.27      0.23      0.25       435
          14       0.00      0.00      0.00        30
          15       0.10      0.60      0.17         5
          16       0.56      0.79      0.66       148

    accuracy                           0.63      4083
   macro avg       0.28      0.45      0.32      4083
weighted avg       0.68      0.63      0.65      4083

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

              precision    recall  f1-score   support

           0       0.88      0.81      0.84      1489
           1       0.48      0.50      0.49       110
           2       0.14      0.33      0.20        58
           3       0.29      0.63      0.40        57
           4       0.49      0.59      0.54        61
           5       0.01      0.04      0.02        24
           6       0.22      0.35      0.27       107
           7       0.18      0.59      0.27        17
           8       0.74      0.59      0.66      1517
           9       0.29      0.44      0.35         9
          10       0.00      0.00      0.00         1
          11       0.14      0.75      0.24         4
          12       0.10      0.27      0.15        11
          13       0.27      0.28      0.28       435
          14       0.14      0.03      0.05        30
          15       0.10      0.60      0.17         5
          16       0.53      0.82      0.64       148

    accuracy                           0.62      4083
   macro avg       0.30      0.45      0.33      4083
weighted avg       0.68      0.62      0.64      4083

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

              precision    recall  f1-score   support

           0       0.88      0.81      0.84      1489
           1       0.48      0.50      0.49       110
           2       0.15      0.33      0.21        58
           3       0.31      0.67      0.42        57
           4       0.49      0.59      0.54        61
           5       0.01      0.04      0.02        24
           6       0.21      0.35      0.26       107
           7       0.18      0.59      0.27        17
           8       0.74      0.61      0.67      1517
           9       0.29      0.44      0.35         9
          10       0.00      0.00      0.00         1
          11       0.14      0.75      0.24         4
          12       0.10      0.27      0.15        11
          13       0.27      0.25      0.26       435
          14       0.12      0.03      0.05        30
          15       0.10      0.60      0.18         5
          16       0.53      0.80      0.64       148

    accuracy                           0.63      4083
   macro avg       0.30      0.45      0.33      4083
weighted avg       0.68      0.63      0.65      4083

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

TrainOutput(global_step=150, training_loss=1.109230982462565, metrics={'train_runtime': 715.7138, 'train_samples_per_second': 103.889, 'train_steps_per_second': 0.21, 'total_flos': 1.207594337004036e+16, 'train_loss': 1.109230982462565, 'epoch': 15.0})

### Temp 4.0 & Batch (256)

In [ ]:
# Cosine w/ 2-cycles -- num epochs 5 -- LR 3e-5
# Train on 5_000 train & eval on full validation
trainer.train()

              precision    recall  f1-score   support

           0       0.85      0.73      0.78      1489
           1       1.00      0.05      0.10       110
           2       0.00      0.00      0.00        58
           3       0.33      0.39      0.36        57
           4       0.42      0.36      0.39        61
           5       0.08      0.25      0.12        24
           6       0.31      0.07      0.12       107
           7       0.25      0.12      0.16        17
           8       0.65      0.66      0.65      1517
           9       0.00      0.00      0.00         9
          10       0.00      0.00      0.00         1
          11       1.00      0.25      0.40         4
          12       0.00      0.00      0.00        11
          13       0.21      0.40      0.28       435
          14       0.00      0.00      0.00        30
          15       0.25      0.20      0.22         5
          16       0.50      0.78      0.61       148

    accuracy                           0.60      4083
   macro avg       0.34      0.25      0.25      4083
weighted avg       0.64      0.60      0.60      4083

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

              precision    recall  f1-score   support

           0       0.85      0.80      0.82      1489
           1       0.81      0.27      0.41       110
           2       0.11      0.07      0.09        58
           3       0.28      0.44      0.34        57
           4       0.44      0.44      0.44        61
           5       0.07      0.29      0.12        24
           6       0.27      0.12      0.17       107
           7       0.20      0.06      0.09        17
           8       0.70      0.60      0.65      1517
           9       0.00      0.00      0.00         9
          10       0.00      0.00      0.00         1
          11       0.00      0.00      0.00         4
          12       0.00      0.00      0.00        11
          13       0.23      0.39      0.29       435
          14       0.00      0.00      0.00        30
          15       0.00      0.00      0.00         5
          16       0.47      0.82      0.60       148

    accuracy                           0.61      4083
   macro avg       0.26      0.25      0.24      4083
weighted avg       0.65      0.61      0.62      4083

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

              precision    recall  f1-score   support

           0       0.86      0.80      0.83      1489
           1       0.60      0.46      0.52       110
           2       0.19      0.28      0.23        58
           3       0.25      0.61      0.36        57
           4       0.47      0.49      0.48        61
           5       0.07      0.33      0.12        24
           6       0.40      0.04      0.07       107
           7       0.24      0.35      0.29        17
           8       0.69      0.73      0.71      1517
           9       0.00      0.00      0.00         9
          10       0.00      0.00      0.00         1
          11       0.15      0.50      0.24         4
          12       0.20      0.09      0.12        11
          13       0.31      0.19      0.23       435
          14       0.00      0.00      0.00        30
          15       0.11      0.40      0.17         5
          16       0.46      0.80      0.59       148

    accuracy                           0.65      4083
   macro avg       0.29      0.36      0.29      4083
weighted avg       0.66      0.65      0.65      4083

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

              precision    recall  f1-score   support

           0       0.86      0.81      0.83      1489
           1       0.57      0.50      0.53       110
           2       0.18      0.33      0.23        58
           3       0.24      0.65      0.35        57
           4       0.53      0.49      0.51        61
           5       0.05      0.17      0.08        24
           6       0.28      0.18      0.22       107
           7       0.20      0.41      0.27        17
           8       0.72      0.66      0.69      1517
           9       0.00      0.00      0.00         9
          10       0.00      0.00      0.00         1
          11       0.33      0.50      0.40         4
          12       0.07      0.09      0.08        11
          13       0.29      0.28      0.28       435
          14       0.00      0.00      0.00        30
          15       0.13      0.40      0.20         5
          16       0.49      0.81      0.61       148

    accuracy                           0.64      4083
   macro avg       0.29      0.37      0.31      4083
weighted avg       0.67      0.64      0.65      4083

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

              precision    recall  f1-score   support

           0       0.87      0.80      0.83      1489
           1       0.59      0.45      0.51       110
           2       0.20      0.29      0.24        58
           3       0.29      0.65      0.40        57
           4       0.52      0.48      0.50        61
           5       0.05      0.17      0.08        24
           6       0.24      0.22      0.23       107
           7       0.26      0.41      0.32        17
           8       0.71      0.66      0.69      1517
           9       0.33      0.11      0.17         9
          10       0.00      0.00      0.00         1
          11       0.25      0.50      0.33         4
          12       0.12      0.09      0.11        11
          13       0.27      0.30      0.28       435
          14       0.00      0.00      0.00        30
          15       0.12      0.40      0.18         5
          16       0.53      0.80      0.64       148

    accuracy                           0.64      4083
   macro avg       0.32      0.37      0.32      4083
weighted avg       0.67      0.64      0.65      4083

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

TrainOutput(global_step=100, training_loss=1.5535578155517578, metrics={'train_runtime': 233.2294, 'train_samples_per_second': 106.269, 'train_steps_per_second': 0.429, 'total_flos': 4025314456680120.0, 'train_loss': 1.5535578155517578, 'epoch': 5.0})

In [ ]:
# Cosine w/ 3-cycles -- num epochs 15 -- LR 3e-5
# Train on subset of train (60/40 train-validation split)
trainer.train()

              precision    recall  f1-score   support

           0       0.63      0.85      0.72       292
           1       0.48      0.30      0.37        33
           2       0.43      0.19      0.27        68
           3       0.45      0.70      0.55        53
           4       0.33      0.47      0.39        57
           5       0.42      0.45      0.43       106
           6       0.58      0.16      0.25       111
           7       0.33      0.02      0.04        42
           8       0.58      0.65      0.62       512
           9       0.40      0.33      0.36         6
          11       0.00      0.00      0.00        17
          12       0.50      0.06      0.11        16
          13       0.48      0.43      0.45       488
          14       0.00      0.00      0.00         4
          15       0.59      0.50      0.54        20
          16       0.62      0.76      0.69       158

    accuracy                           0.54      1983
   macro avg       0.43      0.37      0.36      1983
weighted avg       0.53      0.54      0.52      1983

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

              precision    recall  f1-score   support

           0       0.67      0.82      0.74       292
           1       0.38      0.27      0.32        33
           2       0.36      0.24      0.29        68
           3       0.54      0.62      0.58        53
           4       0.39      0.49      0.44        57
           5       0.43      0.47      0.45       106
           6       0.53      0.28      0.37       111
           7       0.57      0.10      0.16        42
           8       0.57      0.69      0.63       512
           9       0.08      0.17      0.11         6
          11       0.20      0.12      0.15        17
          12       0.21      0.25      0.23        16
          13       0.53      0.41      0.46       488
          14       0.00      0.00      0.00         4
          15       0.46      0.60      0.52        20
          16       0.65      0.76      0.70       158

    accuracy                           0.56      1983
   macro avg       0.41      0.39      0.38      1983
weighted avg       0.55      0.56      0.54      1983

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

              precision    recall  f1-score   support

           0       0.72      0.79      0.75       292
           1       0.32      0.33      0.33        33
           2       0.35      0.26      0.30        68
           3       0.53      0.64      0.58        53
           4       0.36      0.47      0.41        57
           5       0.39      0.50      0.44       106
           6       0.51      0.28      0.36       111
           7       0.62      0.12      0.20        42
           8       0.57      0.68      0.62       512
           9       0.09      0.17      0.12         6
          11       0.27      0.18      0.21        17
          12       0.18      0.12      0.15        16
          13       0.51      0.42      0.46       488
          14       0.00      0.00      0.00         4
          15       0.43      0.50      0.47        20
          16       0.70      0.72      0.71       158

    accuracy                           0.55      1983
   macro avg       0.41      0.39      0.38      1983
weighted avg       0.55      0.55      0.54      1983

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

              precision    recall  f1-score   support

           0       0.68      0.83      0.75       292
           1       0.29      0.30      0.30        33
           2       0.33      0.25      0.29        68
           3       0.49      0.64      0.56        53
           4       0.32      0.49      0.39        57
           5       0.40      0.52      0.45       106
           6       0.50      0.26      0.34       111
           7       0.40      0.10      0.15        42
           8       0.61      0.59      0.60       512
           9       0.08      0.17      0.11         6
          11       0.20      0.06      0.09        17
          12       0.22      0.12      0.16        16
          13       0.48      0.47      0.47       488
          14       0.00      0.00      0.00         4
          15       0.44      0.40      0.42        20
          16       0.69      0.70      0.70       158

    accuracy                           0.54      1983
   macro avg       0.38      0.37      0.36      1983
weighted avg       0.53      0.54      0.53      1983

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

              precision    recall  f1-score   support

           0       0.68      0.83      0.74       292
           1       0.31      0.30      0.31        33
           2       0.33      0.25      0.29        68
           3       0.49      0.64      0.56        53
           4       0.33      0.51      0.40        57
           5       0.40      0.50      0.44       106
           6       0.51      0.26      0.35       111
           7       0.40      0.10      0.15        42
           8       0.61      0.59      0.60       512
           9       0.08      0.17      0.11         6
          11       0.20      0.06      0.09        17
          12       0.22      0.12      0.16        16
          13       0.48      0.48      0.48       488
          14       0.00      0.00      0.00         4
          15       0.47      0.40      0.43        20
          16       0.69      0.71      0.70       158

    accuracy                           0.54      1983
   macro avg       0.39      0.37      0.36      1983
weighted avg       0.54      0.54      0.53      1983

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

              precision    recall  f1-score   support

           0       0.66      0.84      0.74       292
           1       0.32      0.27      0.30        33
           2       0.30      0.37      0.33        68
           3       0.40      0.74      0.52        53
           4       0.31      0.65      0.42        57
           5       0.32      0.64      0.43       106
           6       0.50      0.25      0.34       111
           7       0.33      0.07      0.12        42
           8       0.61      0.63      0.62       512
           9       0.08      0.17      0.11         6
          11       0.22      0.12      0.15        17
          12       0.27      0.19      0.22        16
          13       0.52      0.32      0.39       488
          14       0.00      0.00      0.00         4
          15       0.45      0.50      0.48        20
          16       0.78      0.59      0.67       158

    accuracy                           0.52      1983
   macro avg       0.38      0.40      0.36      1983
weighted avg       0.54      0.52      0.51      1983

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

              precision    recall  f1-score   support

           0       0.64      0.85      0.73       292
           1       0.31      0.39      0.35        33
           2       0.31      0.28      0.29        68
           3       0.56      0.62      0.59        53
           4       0.49      0.42      0.45        57
           5       0.40      0.54      0.46       106
           6       0.46      0.29      0.36       111
           7       0.29      0.10      0.14        42
           8       0.64      0.47      0.54       512
           9       0.09      0.17      0.12         6
          11       0.17      0.06      0.09        17
          12       0.17      0.06      0.09        16
          13       0.47      0.52      0.50       488
          14       0.00      0.00      0.00         4
          15       0.54      0.35      0.42        20
          16       0.60      0.80      0.69       158

    accuracy                           0.54      1983
   macro avg       0.38      0.37      0.36      1983
weighted avg       0.53      0.54      0.52      1983

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

              precision    recall  f1-score   support

           0       0.71      0.82      0.76       292
           1       0.32      0.27      0.30        33
           2       0.35      0.26      0.30        68
           3       0.52      0.60      0.56        53
           4       0.36      0.58      0.44        57
           5       0.40      0.49      0.44       106
           6       0.41      0.32      0.36       111
           7       0.25      0.10      0.14        42
           8       0.61      0.53      0.57       512
           9       0.09      0.17      0.12         6
          11       0.33      0.18      0.23        17
          12       0.21      0.19      0.20        16
          13       0.46      0.48      0.47       488
          14       0.00      0.00      0.00         4
          15       0.50      0.40      0.44        20
          16       0.68      0.73      0.71       158

    accuracy                           0.53      1983
   macro avg       0.39      0.38      0.38      1983
weighted avg       0.53      0.53      0.53      1983

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

              precision    recall  f1-score   support

           0       0.70      0.83      0.76       292
           1       0.32      0.33      0.33        33
           2       0.31      0.25      0.28        68
           3       0.52      0.58      0.55        53
           4       0.38      0.47      0.42        57
           5       0.41      0.49      0.44       106
           6       0.46      0.29      0.35       111
           7       0.31      0.10      0.15        42
           8       0.60      0.62      0.61       512
           9       0.10      0.17      0.12         6
          11       0.33      0.18      0.23        17
          12       0.08      0.06      0.07        16
          13       0.49      0.44      0.47       488
          14       0.00      0.00      0.00         4
          15       0.50      0.40      0.44        20
          16       0.66      0.73      0.69       158

    accuracy                           0.55      1983
   macro avg       0.38      0.37      0.37      1983
weighted avg       0.53      0.55      0.54      1983

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

              precision    recall  f1-score   support

           0       0.70      0.83      0.76       292
           1       0.32      0.33      0.33        33
           2       0.32      0.25      0.28        68
           3       0.52      0.60      0.56        53
           4       0.37      0.47      0.42        57
           5       0.40      0.48      0.44       106
           6       0.45      0.29      0.35       111
           7       0.31      0.10      0.15        42
           8       0.60      0.62      0.61       512
           9       0.10      0.17      0.12         6
          11       0.33      0.18      0.23        17
          12       0.08      0.06      0.07        16
          13       0.49      0.45      0.47       488
          14       0.00      0.00      0.00         4
          15       0.50      0.40      0.44        20
          16       0.66      0.73      0.69       158

    accuracy                           0.55      1983
   macro avg       0.38      0.37      0.37      1983
weighted avg       0.53      0.55      0.53      1983

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

              precision    recall  f1-score   support

           0       0.69      0.82      0.75       292
           1       0.37      0.30      0.33        33
           2       0.36      0.19      0.25        68
           3       0.52      0.57      0.54        53
           4       0.40      0.49      0.44        57
           5       0.47      0.39      0.42       106
           6       0.50      0.23      0.31       111
           7       0.23      0.07      0.11        42
           8       0.59      0.56      0.58       512
           9       0.00      0.00      0.00         6
          11       0.29      0.12      0.17        17
          12       0.14      0.06      0.09        16
          13       0.46      0.55      0.50       488
          14       0.00      0.00      0.00         4
          15       0.56      0.45      0.50        20
          16       0.64      0.74      0.69       158

    accuracy                           0.54      1983
   macro avg       0.39      0.35      0.35      1983
weighted avg       0.53      0.54      0.53      1983

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

              precision    recall  f1-score   support

           0       0.65      0.86      0.74       292
           1       0.38      0.27      0.32        33
           2       0.48      0.16      0.24        68
           3       0.56      0.57      0.56        53
           4       0.41      0.58      0.48        57
           5       0.43      0.40      0.41       106
           6       0.37      0.39      0.38       111
           7       0.27      0.10      0.14        42
           8       0.59      0.58      0.59       512
           9       0.00      0.00      0.00         6
          11       0.33      0.18      0.23        17
          12       0.14      0.06      0.09        16
          13       0.47      0.48      0.48       488
          14       0.00      0.00      0.00         4
          15       0.50      0.40      0.44        20
          16       0.72      0.68      0.70       158

    accuracy                           0.54      1983
   macro avg       0.39      0.36      0.36      1983
weighted avg       0.53      0.54      0.53      1983

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

              precision    recall  f1-score   support

           0       0.68      0.82      0.74       292
           1       0.31      0.30      0.31        33
           2       0.30      0.31      0.31        68
           3       0.52      0.64      0.57        53
           4       0.39      0.54      0.46        57
           5       0.40      0.55      0.46       106
           6       0.41      0.30      0.35       111
           7       0.28      0.12      0.17        42
           8       0.59      0.56      0.58       512
           9       0.00      0.00      0.00         6
          11       0.33      0.12      0.17        17
          12       0.33      0.19      0.24        16
          13       0.50      0.45      0.47       488
          14       0.00      0.00      0.00         4
          15       0.58      0.35      0.44        20
          16       0.66      0.73      0.69       158

    accuracy                           0.54      1983
   macro avg       0.39      0.37      0.37      1983
weighted avg       0.53      0.54      0.53      1983

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

              precision    recall  f1-score   support

           0       0.69      0.82      0.75       292
           1       0.29      0.30      0.30        33
           2       0.34      0.22      0.27        68
           3       0.52      0.64      0.58        53
           4       0.39      0.49      0.44        57
           5       0.38      0.48      0.43       106
           6       0.43      0.33      0.38       111
           7       0.29      0.10      0.14        42
           8       0.59      0.59      0.59       512
           9       0.00      0.00      0.00         6
          11       0.20      0.06      0.09        17
          12       0.17      0.06      0.09        16
          13       0.48      0.48      0.48       488
          14       0.00      0.00      0.00         4
          15       0.50      0.35      0.41        20
          16       0.72      0.68      0.70       158

    accuracy                           0.54      1983
   macro avg       0.37      0.35      0.35      1983
weighted avg       0.53      0.54      0.53      1983

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

              precision    recall  f1-score   support

           0       0.69      0.82      0.75       292
           1       0.30      0.30      0.30        33
           2       0.33      0.22      0.26        68
           3       0.52      0.64      0.57        53
           4       0.39      0.49      0.44        57
           5       0.39      0.48      0.43       106
           6       0.42      0.32      0.36       111
           7       0.29      0.10      0.14        42
           8       0.59      0.59      0.59       512
           9       0.00      0.00      0.00         6
          11       0.33      0.12      0.17        17
          12       0.17      0.06      0.09        16
          13       0.48      0.48      0.48       488
          14       0.00      0.00      0.00         4
          15       0.50      0.35      0.41        20
          16       0.71      0.68      0.70       158

    accuracy                           0.54      1983
   macro avg       0.38      0.35      0.36      1983
weighted avg       0.53      0.54      0.53      1983

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

TrainOutput(global_step=180, training_loss=0.9895760748121474, metrics={'train_runtime': 384.1798, 'train_samples_per_second': 116.118, 'train_steps_per_second': 0.469, 'total_flos': 6473062201312440.0, 'train_loss': 0.9895760748121474, 'epoch': 15.0})

In [ ]:
# Cosine -- num epochs 6 -- LR 3e-5
# Train on subset of train (60/40 train-validation split)

trainer.train()

The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'eos_token_id': None, 'bos_token_id': None}.
W0506 13:07:11.561000 5224 torch/_inductor/utils.py:1679] [1/0_1] Not enough SMs to use max_autotune_gemm mode

              precision    recall  f1-score   support

           0       0.47      0.88      0.62       292
           1       1.00      0.09      0.17        33
           2       0.22      0.03      0.05        68
           3       0.50      0.09      0.16        53
           4       0.30      0.37      0.33        57
           5       0.31      0.42      0.36       106
           6       0.26      0.06      0.10       111
           7       0.00      0.00      0.00        42
           8       0.56      0.40      0.46       512
           9       0.00      0.00      0.00         6
          11       0.00      0.00      0.00        17
          12       0.00      0.00      0.00        16
          13       0.43      0.47      0.45       488
          14       0.00      0.00      0.00         4
          15       0.00      0.00      0.00        20
          16       0.44      0.80      0.57       158

    accuracy                           0.45      1983
   macro avg       0.28      0.23      0.20      1983
weighted avg       0.43      0.45      0.41      1983

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

              precision    recall  f1-score   support

           0       0.67      0.77      0.71       292
           1       0.75      0.18      0.29        33
           2       0.26      0.21      0.23        68
           3       0.45      0.42      0.43        53
           4       0.41      0.44      0.42        57
           5       0.44      0.41      0.42       106
           6       0.41      0.17      0.24       111
           7       0.00      0.00      0.00        42
           8       0.51      0.69      0.58       512
           9       0.20      0.33      0.25         6
          11       0.00      0.00      0.00        17
          12       0.00      0.00      0.00        16
          13       0.50      0.38      0.43       488
          14       0.00      0.00      0.00         4
          15       0.38      0.15      0.21        20
          16       0.53      0.81      0.64       158

    accuracy                           0.52      1983
   macro avg       0.34      0.31      0.30      1983
weighted avg       0.49      0.52      0.49      1983

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

              precision    recall  f1-score   support

           0       0.62      0.83      0.71       292
           1       0.33      0.30      0.32        33
           2       0.37      0.15      0.21        68
           3       0.48      0.58      0.53        53
           4       0.34      0.53      0.42        57
           5       0.39      0.47      0.43       106
           6       0.48      0.18      0.26       111
           7       0.75      0.07      0.13        42
           8       0.59      0.60      0.60       512
           9       0.00      0.00      0.00         6
          11       0.00      0.00      0.00        17
          12       0.00      0.00      0.00        16
          13       0.46      0.51      0.49       488
          14       0.00      0.00      0.00         4
          15       0.41      0.35      0.38        20
          16       0.70      0.63      0.66       158

    accuracy                           0.53      1983
   macro avg       0.37      0.32      0.32      1983
weighted avg       0.52      0.53      0.51      1983

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

              precision    recall  f1-score   support

           0       0.68      0.80      0.74       292
           1       0.39      0.27      0.32        33
           2       0.36      0.18      0.24        68
           3       0.48      0.60      0.54        53
           4       0.36      0.46      0.40        57
           5       0.42      0.44      0.43       106
           6       0.54      0.20      0.29       111
           7       0.75      0.07      0.13        42
           8       0.58      0.62      0.60       512
           9       0.20      0.17      0.18         6
          11       0.00      0.00      0.00        17
          12       0.50      0.06      0.11        16
          13       0.47      0.51      0.49       488
          14       0.00      0.00      0.00         4
          15       0.50      0.35      0.41        20
          16       0.63      0.76      0.69       158

    accuracy                           0.55      1983
   macro avg       0.43      0.34      0.35      1983
weighted avg       0.54      0.55      0.53      1983

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

              precision    recall  f1-score   support

           0       0.67      0.81      0.73       292
           1       0.43      0.27      0.33        33
           2       0.37      0.22      0.28        68
           3       0.47      0.62      0.54        53
           4       0.37      0.46      0.41        57
           5       0.45      0.42      0.43       106
           6       0.47      0.23      0.30       111
           7       0.75      0.07      0.13        42
           8       0.58      0.63      0.61       512
           9       0.14      0.17      0.15         6
          11       0.00      0.00      0.00        17
          12       0.33      0.06      0.11        16
          13       0.48      0.49      0.48       488
          14       0.00      0.00      0.00         4
          15       0.44      0.35      0.39        20
          16       0.63      0.76      0.69       158

    accuracy                           0.55      1983
   macro avg       0.41      0.35      0.35      1983
weighted avg       0.53      0.55      0.53      1983

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

              precision    recall  f1-score   support

           0       0.67      0.81      0.74       292
           1       0.43      0.27      0.33        33
           2       0.36      0.22      0.27        68
           3       0.47      0.62      0.54        53
           4       0.37      0.46      0.41        57
           5       0.44      0.43      0.44       106
           6       0.47      0.23      0.30       111
           7       0.75      0.07      0.13        42
           8       0.58      0.63      0.61       512
           9       0.14      0.17      0.15         6
          11       0.00      0.00      0.00        17
          12       0.50      0.06      0.11        16
          13       0.48      0.49      0.48       488
          14       0.00      0.00      0.00         4
          15       0.44      0.35      0.39        20
          16       0.63      0.76      0.69       158

    accuracy                           0.55      1983
   macro avg       0.42      0.35      0.35      1983
weighted avg       0.54      0.55      0.53      1983

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

TrainOutput(global_step=72, training_loss=1.5004279878404405, metrics={'train_runtime': 164.9784, 'train_samples_per_second': 108.16, 'train_steps_per_second': 0.436, 'total_flos': 2589224880524976.0, 'train_loss': 1.5004279878404405, 'epoch': 6.0})